### ISSUE TITLE
Формулировка концепции блокчейна u-transnet

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#1]
Сеть u-transnet представляет собой систему "программно-аппаратный комплекс", состоящую из собственно транспортной сети и ПО, обеспечивающего управление финансовыми и материальными потоками, сопровождающими функционирование системы.
В рамках работ по текущей задаче предполагается ответить на вопросы:
1. Роль блокчейна u-transnet в экосистеме транспортной сети;
2. Сценарии использования блокчейна в разрезе субъектов системы; 
3. Как блокчейн может управлять развитием и поддержкой транспортной сети;
4. Почему блокчейн должен быть публичным и децентрализованным;

На выходе предполагается получить:
1. верхнеуровневую [диаграмму](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Fdrawings%2Fconcept-full.xml) (набор диаграмм) процессов, протекающих в системе;
2. [документ](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?usp=sharing), фиксирующий ответы на поставленные выше вопросы;
3. презентацию для совета директоров/инвесторов;

UP: запилил [проект](https://github.com/u-transnet/info/projects/1?) под работы над материалами концепта.

UUP: это общая задача, не будем ее отдельно оценивать. Оценивать будем частные задачи, по включению документов, иллюстраций и т.п., типа #18

**Comment by kkrupovich** [comment]
диаграммы будут [тут](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Funity_concept.xml)

**Comment by cptn-solo** [comment]
Необходимо оценить возможность создания _большого_ количества учетных записей - по сути, УЗ должна быть у каждого сенсора, каждой единицы подвижного состава и каждой станции (это только с учетом текущих представлений об архитектуре сети). Возможно, под анализ возможности надо даже создать отдельную задачу, но лучше предварительно собрать несколько подобных вопросов и понять - какие вообще метрики нам надо проанализировать.

**Comment by cptn-solo** [comment]
@githleo  Добавил [таблицу](https://docs.google.com/spreadsheets/d/1nvmLlV-rFJ18H_nYF4-YIPfR9a1ohRMakCJeurUttis/edit?usp=sharing) с примерами проводок, иллюстрирующими экономику токена

**Comment by cptn-solo** [comment]
@githleo Добавил [документ](https://docs.google.com/document/d/1BW7PJPcx_vZhYGBWm-WWfdLe6WyZ-8RCzXY3ZnB1OSU/edit?usp=sharing) с принципами токенизации проектов в рамках платформы

**Comment by cptn-solo** [comment]
@alecvert @githleo [документ](https://docs.google.com/document/d/10YEXtN0SESjgDkPuzyAzMWm3lLzW6dzyEOTzo_XyvIU/edit) под экономику токена

**Comment by cptn-solo** [comment]
[Документ](https://docs.google.com/document/d/1bQqfFamJ_nJRabhpmWODAKq61TKvNK9PW33S4H9vYN4/edit?usp=sharing) с краткой аннотацией экономики под презентацию "введение"

**Comment by kkrupovich** [comment]
<img width="684" alt="screen shot 2017-11-03 at 12 21 17" src="https://user-images.githubusercontent.com/1105555/32372732-27c45144-c0a7-11e7-9cd2-c973bfb97c2f.png">

**Comment by cptn-solo** [comment]
[Доккумент](https://docs.google.com/document/d/1NzLyot56dbcGuMTrQUYYJTNQgr2GT8ry2gSieIcqGps/edit) с описаниями диаграм экономики токена

**Comment by cptn-solo** [comment]
Добавил [новую книгу диаграмм](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Futransnet_concept.xml), там пока одна страница, зафиксировал стороны, участвующие в проектировании и реализации TRANSNET SPACE (новый взгляд, после встречи с @LastWarrior )

Скрин:


<img width="688" alt="screen shot 2017-11-14 at 17 41 59" src="https://user-images.githubusercontent.com/1105555/32785870-94b84c6e-c963-11e7-9e36-3cdc52e82929.png">
