### ISSUE TITLE
Иллюстрация: автономная транспортная система, двоичный код

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#10]
Иллюстрация: что-то про автономную транспортную систему, двоичный код (нолики и единицы) управляющий движением составов на карте-схеме ветвящихся транспортных путей. При этом важно как-то показать "экономическую составляющу" взаимодействия - т.е. эти нолики и единицы - это не только управляющие команды, но и экономические транзакции, сопровождающие перемещение ресурсов. 
[тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSs0JKQ)

**Comment by iSergeevich** [comment]
![default](https://user-images.githubusercontent.com/31988874/31064345-b344aa5a-a754-11e7-8549-7e760fb97152.png) собственно поехали!

**Comment by iSergeevich** [comment]
чтобы все увзреть - смотри максимальное разрешение

**Comment by cptn-solo** [comment]
Шикарное начало. 
Находки, которые я вижу прямо сейчас, и которые надо оставить:
1. бинарный код (1000010010) у стрелок - это точная аналогия, т.к. информация передается по стрелкам, и она - в двоичном виде. 
2. кошелек с ютом и смартфоны с ютом - это норм. надо развивать. 
3. общая стилистика этой диаграммы тоже хороша.

Общие замечания:
1. сервера неплохие, но не совсем понятна их роль на диаграмме, надо будет тебе написать свое вИдение - мне будет проще его скорректировать, чем расписать "с нуля". Пиши прям тут в комменте.
2. чтобы тебе было проще - задаю предметные вопросы, см. картинки ниже и поясняй - что ты имел ввиду:
<img width="67" alt="screen shot 2017-10-02 at 10 06 24" src="https://user-images.githubusercontent.com/1105555/31067031-73de4790-a759-11e7-83ab-860b0b67c097.png"> 1 это "         "
<img width="44" alt="screen shot 2017-10-02 at 10 06 18" src="https://user-images.githubusercontent.com/1105555/31067034-7414976e-a759-11e7-9014-d21044f9ae5a.png"> 2 это "         "
<img width="45" alt="screen shot 2017-10-02 at 10 06 09" src="https://user-images.githubusercontent.com/1105555/31067032-74110770-a759-11e7-836d-c3eeeb99134b.png"> 3 это "         "
<img width="63" alt="screen shot 2017-10-02 at 10 05 56" src="https://user-images.githubusercontent.com/1105555/31067033-74126642-a759-11e7-9470-54a713e8048d.png"> 4 это "         "

**Comment by iSergeevich** [comment]
1. сервера - место где происходит майниг верно? 
ну вот я показал это правда не знал уместно или нет.

2. поясняю:
1 это случайность, не убрал значек
2 это круговорот крипты
3 это остановка (станция)
4 это блокчейн, ну я его так вижу, тоже не знаю уместно тут или нет

**Comment by cptn-solo** [comment]
Принял. Сформулирую ответы и корректировки твоего мировоззрения чуть позже :)

**Comment by iSergeevich** [comment]
гран мерси!

**Comment by cptn-solo** [comment]
В общем, так:
1. Кошелек с монетками надо оставить только там, где "человек" входит в "станцию" - это важно, т.к. базовый актив транснет используется только для расчетов за услуги Сети (и для инвестиций, но они здесь за скобками у нас остаются).
2. серверы, управляющие траффиком, действительно делают это "в двоичном коде", это норм. Но они не оперируют Юттом, т.ч. монетки оттуда надо убрать. 
3. блокчейн регистрирует транзакции. Транзакции возникают в процессе взаимодействия элементов сети между собой и с внешними агентами (пассажирами). Т.о. Блокчейн (каким бы мы его не изображали на слайдах) должен присутствовать именно в точках взаимодействия (турникет пропускающий пассажиров, вагонетка, проходящая через сенсор на путевой структуре, станция, принимающая вагонетку и т.п.)
4. потом отдельно надо подумать про связь серверов и блокчейна, про связь серверов друг с другом. Возможно, надо будет отображать две параллельные структуры - сплошные линии - путевая структура и пунктирная линия, дублирующая сплошную с серверами, расположенными прямо на пунктире. 
5. Вообще, предлагаю с учетом п.п.4 перерисовать вариант двойной линии (сплошная+пунктирная) с шариками серверов на пунктирной линии и стрелками от пунктирной к сплошной, передающими двоичные команды в сплошную (как сейчас у тебя нарисовано), но каждая стрелка, ведущая из пунктирной линии в сплошную, должна делать это:
i. в точках, описанных в п.п.3, и
ii. делать это "посредством блокчейна" - т.е. на этих передающих управляющие команды стрелках можно разместить символ блокчейна, каким бы он ни был.

Как понял, прием

**Comment by iSergeevich** [comment]
![2](https://user-images.githubusercontent.com/31988874/31200116-1cdba4ee-a973-11e7-9c37-c7a28e3ab96d.png)

**Comment by iSergeevich** [comment]
выноски с цифро-значениями просто для примера

**Comment by iSergeevich** [comment]
![3](https://user-images.githubusercontent.com/31988874/31200196-6b3a60e4-a973-11e7-9241-27c6305e00ad.png) и вариант с двоичным кодом

**Comment by cptn-solo** [comment]
последний вариант отличный, прикладываю только принципиальную схему взаимодействия, чтобы проиллюстрировать свои предыдущие комментарии
<img width="724" alt="screen shot 2017-10-05 at 12 01 00" src="https://user-images.githubusercontent.com/1105555/31219140-12c39172-a9c5-11e7-8b49-daadb45ee3ed.png">

бочки - это серверы - база данных, блокчейн в общем случае.
ромб - это вагонетка, на моих диаграммах она часто так отображается.

Смысл - пунктирная линия - это сеть информационная, сплошная - сеть физическая. Стрелки тоже - пунктирные - гоняют объемы ресурсных токенов между объектами физ. сети, сплошные - гоняют команды управления в двоичном виде и обратную связь по этим командам (прошла/не прошла, выполнена/невыполнена)

**Comment by cptn-solo** [comment]
Не знаю, вот что-то среднее между моим видением и Ваниным
<img width="686" alt="screen shot 2017-10-05 at 16 20 21" src="https://user-images.githubusercontent.com/1105555/31229374-24b4ea42-a9e9-11e7-9904-917b1e242063.png">

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich вагонетку не надо рисовать как вагонетку. Ваня , посмотри как выглядить юнитрак https://www.youtube.com/watch?v=UVHbUTsse98 .

Пока как-то слабовата схема. Турникет, будет ли вообще? Или это сенсор на станции, который автоматом будет списывать базовый актив?

Мне лично схема непонятна сейчас.
Надо 100% делать пояснения, если будем оставлять в подобном виде.

**Comment by cptn-solo** [comment]
> Мне лично схема непонятна сейчас.

Еще раз, цель данной иллюстрации - показать управление технической инфраструктурой (физической сетью) посредством транзакций в блокчейне (цифровой сети). Как и что должно быть нарисовано - вопросы к правому полушарию @iSergeevich - пускай генерит варианты, мы отсеиваем.

**Comment by iSergeevich** [comment]
@alecvert @kkrupovich тогда вместо секторов и областей на инфографике будут иконки, ибо все вместе это перебор для глаза

**Comment by cptn-solo** [comment]
> @alecvert @kkrupovich тогда вместо секторов и областей на инфографике будут иконки, ибо все вместе это перебор для глаза

Ваня, ты перепутал задачу. этот коммент видимо был для #9

**Comment by iSergeevich** [comment]
@kkrupovich твоя интерпритация - в нижней части инфографики
по иконкам есть вопросы? спрашивайте - отвечу
![4](https://user-images.githubusercontent.com/31988874/31493416-979f95c8-af68-11e7-99af-c4f606e27c72.png)

**Comment by alecvert** [comment]
@iSergeevich @kkrupovich уже лучше , что обозначают цвета?
http://prntscr.com/gxz6h7 станция? лучше нарисовать как станцию.
http://prntscr.com/gxz6wr это что? 
Проще дать условные обозначения 
Я не понимаю вообщем эту схему прям досконально. Но выглядит качественно

**Comment by cptn-solo** [comment]
@iSergeevich по пунктам:
1. В шариках буквы A, B, C, D, E - это лишнее и в концепции такого нет. Даже так я бы сказал - в концепции на А2 (экономика токена) эти буквы есть, но означают совершенно конкретные вещи - это активы подвижного состава, станций и путевой структуры. Это надо убирать, а то запутаемся;
2. на нижней левой схемке (по мотивам моей схемы, я так понимаю) - норм буквально все, но НА ПРАВОЙ картинке мы опять видим, что @iSergeevich не понял, что означает пунктирная линия - она не может нести груз, это "цифровая" сеть, виртуальная. Все, что касается блокчейна (его транзакции, учетные записи станций, контейнеров, датчиков) - живет на пунктире, вся физическая часть (сами станции, контейнеры и датчики) - живет на сплошной линии. От пунктирной линии идут двоичные команды в сплошную, от сплошной - инициируются транзакции блокчейна (в активах F, H, D) - в пунктирную.

**Comment by iSergeevich** [comment]
@kkrupovich понял. буквы уберу. пунктир очищу. цвета были для примера. сделаю в цветах лого. мятные или лайм оттенки

**Comment by iSergeevich** [comment]
@alecvert для тебя сделаю справочник по иконкам, так как @kkrupovich уже знает обозначения моих иконок

**Comment by iSergeevich** [comment]
![2](https://user-images.githubusercontent.com/31988874/31623533-24beddd0-b2b9-11e7-84a5-f3be8e074325.png)
вместе с иконками

**Comment by iSergeevich** [comment]
![5](https://user-images.githubusercontent.com/31988874/31647223-61e292da-b320-11e7-8ede-c9739b8b95da.png)
![default](https://user-images.githubusercontent.com/31988874/31647224-620aeb18-b320-11e7-8d70-fdc6ac2ee037.jpg)

**Comment by cptn-solo** [comment]
Ну, тут, похоже, никаких особых изменений не произошло, только иконки... Не знаю, это хорошо, наверное, что у нас теперь есть справочник иконок - но хз. Иллюстрации должны брать не этим.

**Comment by cptn-solo** [comment]
Все же я бы продолжил попытки _объединения_ моих пояснений и Ваниной концепции для этой иллюстрации.

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich давайте голосом поштурмуем над иллюстрациями

**Comment by iSergeevich** [comment]
да я добавил иконки и изменил цвета
