### ISSUE TITLE
Ознакомительная презентация для сбора фидбэка (без символики)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#14]
Но пока без фирменного стиля, так как название пока показывать не будем, так как не запустим ещё сайт
просто на приятном фоне какой у нас будет, без символики и лого
слайды презы в power point

Слайд 1
Существует ли мир IoT

Ведущие исследователи говорят к 2025 году 500 миллиардов вещей будут подключены к интернету.

Слайд 2
Всеобщая роботизация
Картинки роботов- швейцаров , поваров и т д, дронов, беспилотных автомобилей

Слайд 3
Мобильность 5.0 
И картинки подвижных составов SW  , станций и т д

Слайд 4
Шестой технологический уклад.

Слайд 5
Новое цифровое пространство – Transnet Space. Какую-то графику надо для обозначения. 
Давай, например, схематичные иконки подв. Состава , Станции, путевой структуры, пользователя и их взаимодействие.

Слайд 6
Сегодняшний рынок первичных размещений токена.
Примеры Tezos сумма сбора, FileCoin сумма сбора , EOS сумма сбора

Слайд 7 - пока не делаем на 4 ноября, пока не показывается название.
Капитализация токена после первичного размещения

Взять отсюда первые 10 позиций : https://icostats.com/roi-since-ico 

Слайд 8
Новая цифровая экономика и её синхронизация с реальной экономикой

 Картинка 76,5 трлн $ реальная экономика и >150 млрд$ цифровая криптоэкономика

**Comment by cptn-solo** [comment]
@iSergeevich @alecvert смотрите, какую шикарную презу нашел по bitshares:
https://bitshares.org/media/2015_bitshares_infographic_en.pdf

Сперто [отсюда](https://bitshares.org/contact/) (там есть еще медиа-кит, откуда можно иконку битшар подрезать в svg какую-нибудь)

**Comment by iSergeevich** [comment]
презентация больше 30мб, поэтому загружаю на гуглодиск
https://drive.google.com/open?id=0B5aDnmOCGYFhT0lOdnVQbWJNdHM

**Comment by kkrupovich** [comment]
@iSergeevich @alecvert парни, а не хотите повернуть картинку вокруг вертикальной оси на 180градусов, чтобы символ % этот слайд напоминал?
<img width="710" alt="screen shot 2017-11-02 at 21 54 16" src="https://user-images.githubusercontent.com/1105555/32344603-78b15762-c018-11e7-9193-3fd225379919.png">

**Comment by alecvert** [comment]
@iSergeevich 
1 слайд изменить : Презентация концепта блокчейн платформы для SkyWay и Transnet, не надо лого пока что наш, ну сделай и такой и такой вариант. Я пока не решил, буду показывать лого в екб или нет. Так как идиоты какие-нибудь могут снимать на телефон, выложить в сеть и потом на нас сделают 4-й скам уже на существующие названия, я этого боюсь.

Здесь вместо картинки на фон здесь http://prntscr.com/h5fi24 вставить в той же стилистике : https://user-images.githubusercontent.com/31988874/31648584-fe45591c-b327-11e7-940e-6261643637de.png 

2, 3 слайд норм, ты уловил идею, молодец.

4 слайд 
http://prntscr.com/h5fq2k вверху подпиши мобильность 1.0 
http://prntscr.com/h5fqfo 2.0 и здесь должна быть лошадь с телегой http://prntscr.com/h5fqnf , то есть просто с лошадью убери 
http://prntscr.com/h5fqu5 это объедини паровой двигатель и бензиновый и 3.0 подпиши, причём контуры выноска http://prntscr.com/h5froi должны включать в себя картинки, чтоб красиво было, 
то есть сделай её больше, если надо
http://prntscr.com/h5fth3 здесь включи беспилотный автомобиль и умный транспорт, это 4.0
http://prntscr.com/h5ftsr выбери эту картинку http://prntscr.com/h5fuhn вставь иконку SW 5.0 
5+ - это SW + blockchain, добавь 

5 слайд назовём Глобальная единая сеть Transnet
Возьми вот эту картинку https://user-images.githubusercontent.com/31988874/31648584-fe45591c-b327-11e7-940e-6261643637de.png

6 слайд Transnet Space
вставь  https://user-images.githubusercontent.com/31988874/31635209-68533c50-b2df-11e7-94a0-a1e7603267bd.jpg

7 слайд вот этот http://prntscr.com/h5fydg , но ютт иконку убери, подвижной состав, станцию ( лучше ещё дополнительно взять, которая высотная только с зелёной крышей http://prntscr.com/h5fz2s ), человечка лучше этого http://prntscr.com/h5fzib, только без значка коина

8 слайд 
Попробуй сделать инфографикой эти составляющие как представляешь, закглавными буквами я специально отметил то, что нужно показать и написать, далее идёт описание, чтоб ты понял :

1. ТОКЕНИЗАЦИЯ Наличие инструментария для оцифровки показателей бизнес-планов, предполагающих финансирование эксплуатации объектов проекта вплоть до выхода проекта на самоокупаемость и получения прибыли. Это, в свою очередь, позволяет:
а) УПРОЩЕНИЕ Упростить взаимодействие между сторонами инвестиционного процесса - все финансовые транзакции осуществляются внутри единого информационного и экономического пространства; 
б)СОКРАЩЕНИЕ Сократить сроки согласования и запуска проектов - возможно публичное голосование по приоритетам финансирования этапов работ;
в)ПРОЗРАЧНОСТЬ Сделать полностью прозрачными потоки как привлеченных в токенизированные проекты средств, так и возвращаемых уже эксплуатирующимися объектами;
2. АВТОМАТИЗАЦИЯ Автоматизация финансовых транзакций, осуществляемых непосредственно объектами физической инфраструктуры с активами, находящимися на их собственных балансах в блокчейне TRANSNET SPACE;
3. ДЕЦЕНТРАЛИЗАЦИЯ Отсутствие единого центра отказа благодаря децентрализованной архитектуре решения, реализуемого U▪TECH, и, как следствие, обеспечение гарантии подлинности и неизменности данных финансовых и материальных  транзакций, совершаемых в рамках Платформы;
4. МАСШТАБИРУЕМОСТЬ. Количество совершаемых транзакций в сек. может быть от 100 000 транзакций до уже на сегодняшний момент до млн транзакций и далее до трлн транзакций в секунду
4. СТИМУЛЫ Наличие средств стимулирования и подтверждения качества проведения любого вида работ в рамках адресного проекта (Квалификационный токен для квотирования и сертификации);
Наличие возможности создания токенов адресных проектов и их полностью децентрализованной эмиссии в объеме заложенного в бизнес-план финансирования, включая юридическую, маркетинговую, инженерную составляющие. Каждый токен адресного проекта, например г.Абу-Даби, обеспечивается базовым активом UTT блокчейн-платформы TRANSNET SPACE; 
Обеспечение возможности привлечения финансирование как в виде криптовалют, так и в фиатных средствах от инвесторов со всего мира, в том числе фондов и институциональных инвесторов;
5. УСКОРЕННЫЙ ROI Обеспечение условий для ускорения возврата инвестиций. В зависимости от роста курса токена UTT при его выходе на внешние крипто биржи, стоимость токена адресного проекта будет также увеличиваться.

9 слайд http://prntscr.com/h5g1zo

10 слайд http://prntscr.com/h5g25q

11 слайд http://prntscr.com/h5g2bo 

12 слайд добавь We must unite - Мы должны объединиться http://prntscr.com/h5g2qf Спасибо за внимание ок

Ещё пожелание сделай всё на белом фоне, но не чисто белом, а чтоб также круто слайд выглядел с оцифрованным шаром , может мятный какой-то , поиграйся

**Comment by cptn-solo** [comment]
@alecvert @iSergeevich коллеги, добавил задачу (#15) под "вводную" презу и в ней ссылка на текст Краткой аннотации - мало ли для этой презы вам пригодится

**Comment by iSergeevich** [comment]
вуаля!
[презентация 2.0.pdf](https://github.com/u-transnet/info/files/1440416/2.0.pdf)

**Comment by iSergeevich** [comment]
вуаля!
[презентация 2.1.pdf](https://github.com/u-transnet/info/files/1442244/2.1.pdf)

**Comment by iSergeevich** [comment]
без упоминания ЮТТ
[презентация 2.2.pdf](https://github.com/u-transnet/info/files/1443448/2.2.pdf)

**Comment by cptn-solo** [comment]
@iSergeevich @alecvert парни, закрываю? раз уже ушла в народ. Надо будет что-то поправить - будет задача на доработку.
