### ISSUE TITLE
"Вводная" презентация в виде схемы движения токена

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#15]
Изометрия с сайта, плюс краткое введение (transnet и iot)
Есть задача #19 , из который можно взять текст за основу презентации (Краткая аннотация проектируемой платформы (под перевод))
В дополнение к этому документу (аннотации) в презентацию необходимо включить схемы, поясняющие экономику токена и пояснения к ним (два-три слайда), например:

A6.1.Строительство/производство (кратко):
<img width="486" alt="screen shot 2017-11-10 at 00 55 44" src="https://user-images.githubusercontent.com/1105555/32631651-edd8ebb0-c5b1-11e7-9d65-e2d5c1f8e537.png">

A7.1.Эксплуатация (кратко):
<img width="582" alt="screen shot 2017-11-10 at 00 54 26" src="https://user-images.githubusercontent.com/1105555/32631668-fe37b31a-c5b1-11e7-9b84-875bda4f2970.png">

UP: задачу можно оценивать независимо от #19 , т.к. ту надо решать раньше, чем эту, и ту я беру себе, видимо.

**Comment by cptn-solo** [comment]
@alecvert @iSergeevich присоединяйтесь, @iSergeevich если берешься за задачу - предлагаю начать процесс оценки (сроки, стоимость)

**Comment by alecvert** [comment]
@kkrupovich вроде как диаграммы выглядят простыми, но без обращения к полным диаграммам не до конца будет понятно тому, кто будет смотреть простые упрощённые версии.

Нужно проговорить. Возможно в простых, что в этой задаче указаны чего-то не хватает.

**Comment by cptn-solo** [comment]
> Нужно проговорить. Возможно в простых, что в этой задаче указаны чего-то не хватает.

@alecvert думаю для целей презентации нужно менять "точку зрения", с которой мы смотрим на эти диаграмы - нужно что-то аналогичное [этому](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Futransnet_concept.xml) (это новая книга диаграмм, общий взгляд на проект, с учетом фидбэка от LastWarrior) ![](https://user-images.githubusercontent.com/1105555/32785870-94b84c6e-c963-11e7-9e36-3cdc52e82929.png)

**Comment by iSergeevich** [comment]
@kkrupovich, если возьмусь - не раньше середины следующей недели.
срок от 3 часов до 2 дней максимум
цену нужно обсуждать

**Comment by cptn-solo** [comment]
@alecvert @iSergeevich Возможно это норм и даже хорошо, т.к. я хочу переписать текст в другом ключе.

**Comment by iSergeevich** [comment]
@kkrupovich, делай так, как считаешь нужным, дай знать когда конкретика будет.
и на перспективу, ребят: если есть необходимость у меня чего-то спросить - пишите пожалуйста мне в личку или маякните по телефону. у меня в телеграмме 12 чатов и все разрываются. если смотреть каждый раз сообщения можно телефон из рук не выпускать. спасибо за понимание

**Comment by cptn-solo** [comment]
@iSergeevich емнип ты телеграмм на телефон поставил под наш проект. Уже 12 чатов?! ;)) 
По существу - это ты маякни, как появится желание порисовать. У нас для тебя всегда найдется работа и теплое слово, подкрепленное материальным вознаграждением ;) Не парься.

**Comment by iSergeevich** [comment]
@kkrupovich ну я просто понял что nu это удобно, а теперь не знаю как его заглушить)))
и, спасибо!
но скорее не желание, а время

**Comment by cptn-solo** [comment]
Задача в текущей постановке не актуальна, создал #22
