### ISSUE TITLE
Наше вИдение / Our vision

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#17]
Презентация в максимально эффектной подаче, максимум одна минута, зарождение и генезис псевдо-живого организма ([UNI-C](https://github.com/u-transnet/info/blob/master/UNI-C.md)) (скелет, кровеносная, нервная система) + "сознание" в сети "нейронов", реализованное в узлах блокчейн-сети и контрактах, консенсусе.

**Comment by cptn-solo** [comment]
@alecvert сюда исполнителем надо ставить того человека, о котором вы говорили, сценарий нужно расписывать прямо здесь (редактировать описание задачи, можно предварительно предлагать в комментариях прям тут, картинки прикладывать). 
Концепцию UNI-C зафиксировал в файле info/UNI-C.md , закоммитил в ветку master .

**Comment by cptn-solo** [comment]
@icggithub салют! Рад видеть тебя в участниках проекта :) 
В рамках этой задачи мы хотим проводить обсуждение и проработку сценария, шарить какую-то графику и примеры и т.д. Для каких-то больших кусков работы (проработка фрагментов или вариантов) будем создавать отдельные задачи, чтобы не перегружать бэклог основной задачи.

**Comment by icggithub** [comment]
Привет всем!
Рамки задачи понятны. Попробуем порешать её. И - решить)

С уважением,
ИС

15 ноября 2017 г., 21:08 пользователь Konstantin Krupovich <
notifications@github.com> написал:
