### ISSUE TITLE
Формулировка алгоритма и характеристик процедуры распределения токена

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#2]
Можно проанализировать процедуру форка основных цепей (steemit -> golos, bitcoin -> bitcoin cash), а так же алгоритмов востребования токенов (claim) после события форка. 
Также рассматриваем варианты ввода в обращение базового актива и в целом - взаимодействие между участниками в процессе формирования Сети

**Comment by cptn-solo** [comment]
@alecvert @githleo это не касается токенов адресных проектов. В рамках данной задачи мы определяемся с "окнами", партнеркой и т.п.

**Comment by cptn-solo** [comment]
@alecvert @githleo судя по недавним обсуждениям, видимо, тут мы будем формировать экспертное обсуждение схемы с конституцией, заверителями, управлением размером вознаграждения за блок, и т.д.

**Comment by cptn-solo** [comment]
Создана задача, в рамках которой проводится проработка стратегии размещения #28

**Comment by cptn-solo** [comment]
По сути, до сих пор мы проектировали только внутренние механизмы финансирования и эксплуатации инфраструктурных и адресных проектов. Теперь мы подошли к анализу привлечения в проект внешних крипто-инвесторов, заинтересованных в эмиссии активов инфраструктурных и адресных проектов TRANSNET SPACE по мере запуска этих проектов. 
Важно понимать, что выводимый на внешний рынок базовый актив блокчейна по мере его возвращения на внутренний рынок в процессе востребования владельцами, например, ERC20 токена, совокупный стейк таких "внешних" инвесторов, не являющихся заверителями блокчейна, может иметь значительный вес в сравнении с совокупным стейком заверителей. 
Поэтому нужно правильно рассчитать пропорцию базового актива, выводимого из системы через процедуру распределения,  и защитить интересы стейкхолдеров-заверителей блокчейна.

**Comment by cptn-solo** [comment]
Фиксируем с @alecvert вариант решения - в распределении участвует не базовый актив, а транзитный актив первого инфраструктурного направления - UIA UTECH.UTCORE. Участникам процедуры распределения будет предоставляться возможность востребования транзитного актива на свой счет в u-transnet и далее либо обменять его на MPA UTCORE 1:1 (если это будет экономически выгодно, т.к. UTCORE привязывается к USD или другой внешней валюте), либо вывести через шлюз в Bitshares DEX и продавать его там, например, в паре к эфиру/биткойну или любой другой доступной в Bitshares DEX валюте.
При этом токен UTCORE (текущее финансирование разработки U-TECH), уже присутствующий в Bitshares DEX, получает полноценный статус транзитного актива u-Transnet, текущие держатели этого токена получают возможность его продажи по рыночной цене, либо вывода через шлюз в u-Transnet. 

TBD: нужна задача на шлюз между Bitshares и u-Transnet для транзитного актива.

**Comment by cptn-solo** [comment]
Создал [задачу](https://github.com/u-transnet/codebase/issues/4) на реализацию ERC20 и процедур распределения и востребования.
Создал [задачу](https://github.com/u-transnet/codebase/issues/39) на шлюз под транзитный инфраструктурный токен между u-Transnet и Bitshares.

**Comment by cptn-solo** [comment]
@alecvert по хорошему надо рассмотреть еще один сценарий распределения - выставление ордеров на продажу по максимально доступной цене через заданные промежутки времени. Сценарий предполагает наличие шлюзов (например, в крипту, но можно использовать и UIA на фиатные валюты при наличии аффилиатов, готовых участвовать в качестве фонда, аккумулирующего фиат) или p2p обменников на валютные MPA.  Тогда любой желающий _купить_ токен направления (можно сразу продавать MPA) будет заинтересован поставить ордер на покупку по максимальной цене, тем самым максимизируя выручку продающей стороны и создавая заинтересованность в среде заверителей, которые в данном случае будут являться стейкхолдерами. Можно развить идею и ранжировать ордера в окнах при помощи продающего бота, который будет формировать очередь из предложений на продажу MPA направления, поступающих от стейкхолдеров - таким образом первый, кто решит вложить стейк в данное направление будет защищен от других участников (фиксированным объемом окна) и сможет продать свой объем быстрее. Можно дополнить схему взвешиванием для случаев, когда в каждое окно после его октрытия могут добавляться предложения от новых участников-стейкхолдеров, но тут сложнее, сходу не опишу. 
Спасибо @LastWarrior за информацию об этом сценарии. Изначально сценарий предложен Ларимером в качестве "идеального" уже после запуска распределения EOS.

**Comment by alecvert** [comment]
@kkrupovich то есть по сути модель децентрализованного размещения?

**Comment by alecvert** [comment]
@kkrupovich надо помнить, что заверитель под стейк может выпустить токен направления или АП, но не ютт актив usd,  и т д

**Comment by cptn-solo** [comment]
@alecvert 
> то есть по сути модель децентрализованного размещения

по сути - да, т.к. мы в такой схеме управляем продажей токена направления, но не его покупкой. Если мы будем выставлять в микро-окнах ордера на продажу в p2p рынках (uttUSD, etc) - то участвовать смогут абсолютно все держатели uttUSD, получившие их любым доступным способом. Плюс, в случае реализации стандартных трастовых шлюзов, например, ETH/BTC, участниками будут все желающие, зашедшие в u-Transnet через эти крипто-валюты, но это частично привнесет централизацию - сам вход будет зависеть от работы шлюзов. 
Если же предварительно реализовать [шлюз нового типа](https://github.com/u-transnet/codebase/issues/40) (это развитие нашего исследования возможности atomic swap) - то размещение будет полностью децентрализованным (по крайней мере на столько, насколько будет децентрализовано сообщество Заверителей блокчейна u-Transnet).

> но не ютт актив usd

А кто тогда будет выпускать uttUSD? Весь? Мы не можем ограничивать никого в выпуске чего бы то ни было, тут основную роль играет совершенно другая мотивация - заверитель будет вынужден взвешивать все "за" и "против" печати того или иного актива в своей конкретной ситуации. Санкции к нему будут применяться (снятие голосов других заверителей) только в том случае, если этот заверитель _вообще ничего_ не будет выпускать - тогда его естественным образом разголосуют, просто чтобы соблюсти с ним паритет. Это будет стимулировать активную позицию заверителей, а не пассивную, как в современном Bitshares, где сидит три кита, управляющие всем, а весь остальной рынок остается вообще без ликвидности и возможности куда-либо расти.
