### ISSUE TITLE
Наем сотрудников

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#20]
**Тут собираем вакансии - открытые, закрытые, предполагаемые**

Реестр(блокчейн): с++, python
Веб (сайтострой):js/html/css (reactive) #25 
Веб (фуллстек):js/python #37 
Техническая инфраструктура: системный администратор unix
Общее для маркетинга и сайтостроя:
дизайн (сайты, включая графику) #21 
проектировщик интерфейсов (web)

Системный аналитик/архитектор: #31 
Журналист/обозреватель/Автор: #33 

Как мы работаем:

- [Схема вознаграждения](https://github.com/u-transnet/info/wiki/2.-Принять-участие)

- [Схема роста](https://github.com/u-transnet/info/wiki/2.1.-Рост-в-команде)

**Comment by jackal1527** [comment]
- виртуозное владение Фотошопом, Иллюстратором и Корелом.
- наличие портфолио или работ приветствуется (повлияет на обсуждение ЗП)
- приветствуется системное мышление
- умение работать в команде, брать ответственность и проявлять инициативу в возложенных задачах.

**Comment by cptn-solo** [comment]
Под дизайнера (выше) создал #21

**Comment by cptn-solo** [comment]
Под верстальщика и вообще - под веб-разработку создал #25

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert парни, ребят взяли, т.ч. пока вакансии закрываем, при необходимости - переоткрываем, актуализируем - и используем повторно. ссылки на закрытые задачи тут остаются, эта задача не закрывается. Сюда кстати можете писать планы по ресурсам, если придумаете кто нам нужен еще

**Comment by cptn-solo** [comment]
Так, @jackal1527 @alecvert переоткрываю #21 т.к. один боец оказался так себе, не боец.

**Comment by cptn-solo** [comment]
@alecvert #32 начинаем собеседовать.

**Comment by cptn-solo** [comment]
@alecvert 
Надо зафиксировать где-то схему роста: 
[собеседование] - 0.5 ~ 0.6 - 0.7 - 0.8 - 0.9 - 1.0 ~ [собеседование]
где 0.5-1.0 - это доля UTDEV.SKILL от максимально возможной для бюджетной позиции, соответствующей этой вакансии, передаваемая сотруднику в качестве месячного объема квалификационного токена для исчисления дневной ставки исходя из 1/20 месячного объема. 
Например, если макс. ставка составляет 2000 UTDEV, то 0.5 (испытательный срок) составит 1000 UTDEV, а значит сотрудник получает в начале периода 1000 UTDEV.SKILL для внесения залога под оцененные и принимаемые в работу задачи. По мере выработки переданного объема скилла, следующий объем (в случае успешного прохождения испытательного срока) составит уже 0.6, и далее будет подниматься на 0.1 в каждый следующий транш. С учетом того, что рабочих дней в месяце больше 20, сотрудник фактически растет с 0.5 до 1.0 быстрее, чем за 5 месяцев.

**Comment by alecvert** [comment]
@kkrupovich Надо зафиксировать где-то схему роста:
[собеседование] - 0.5 ~ 0.6 - 0.7 - 0.8 - 0.9 - 1.0 ~ [собеседование]
Да, поддерживаю

**Comment by cptn-solo** [comment]
@alecvert 
> Да, поддерживаю

Выкатил в [вики](https://github.com/u-transnet/info/wiki/2.1.-Рост-в-команде), но важно (на мой взгляд) стараться все-таки фиксировать максимальную ставку и искать кандидатов под нее, а не плясать под дудку любителей прокатиться на ICO

**Comment by cptn-solo** [comment]
Для публикаций хочу использовать картинку
<img width="231" alt="screen shot 2017-12-06 at 16 17 47" src="https://user-images.githubusercontent.com/1105555/33663552-7b51c81e-daa1-11e7-8abf-1447452b3af3.png">

просьба не удалять коммент
