### ISSUE TITLE
[ВАКАНСИЯ] Ищем дизайнера

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#21]
**Требования к кандидатам**

1. Bиртуозное владение Sketch, Аdobe CC (AI, PSD)
3. Наличие портфолио или работ **обязательно**.
4. Аналитеческое (системное) мышление
5. Умение и опыт удаленной работаты в команде
6. Умение решать отрытые задачи. 

Фуллтайм, парттайм, удаленная работа. Решение ОТКРЫТЫХ задач.

Формальных условий получения максимальной оценки нет, но важно понимать, что чем более самостоятельно функционирует кандидат, и чем меньше за него делают/переделывают другие члены команды - тем выше шанс вписаться на максимум (а возможно и задать новую планку)

**Текущие задачи, предполагаемые к решению кандидатом:**

Дизайн Вебсайта (в дальнейшем - сайты внутренних проектов и адресных проектов) - репозиторий [www-teaser](https://github.com/u-transnet/www-teaser/projects/1?):

- [Проработка "шапки сайта-тизера"](https://github.com/u-transnet/www-teaser/issues/13)

- [Отрисовка иконок в векторе в стиле концепта сайта](https://github.com/u-transnet/www-teaser/issues/15)

- [Отрисовка иллюстрации по оцифровке точки системы](https://github.com/u-transnet/www-teaser/issues/23)

- [Участие в дальнейших итерациях макетирования сайта-тизера](https://github.com/u-transnet/www-teaser/issues/8) (там же в описании задачи есть пара ссылок на wiki)

- Вообще - довольно много задач, связанных с дизайном сайта (см. [задачи с тегом art](https://github.com/u-transnet/www-teaser/issues?q=is%3Aopen+is%3Aissue+label%3Aart))

Иллюстрация концепций и идей (инфографика) резентаций (репозиторий [info](https://github.com/u-transnet/info/projects/1?) - вообще богат задачами для творчества ;)):

- Дизайн для презентаций в контексте общей стилистики проекта](https://github.com/u-transnet/info/issues/4)

**Comment by kkrupovich** [comment]
Задача вроде выполнена. 
Разбор полетов:
1. мы работаем по схеме, зафиксированной в wiki (раздел [Принять участие](https://github.com/u-transnet/info/wiki/2.-Принять-участие)): 
>п.п.5 : фиксируем в описании задачи номер блока с транзакцией перевода, учетку исполнителя в бч Bitshares, предварительный срок реализации;

Тут указана учетка github. Зачем? и так ясно что это @UspenskyDritry исполнитель, в обратную ссылку надо ставить учетку Bitshares.

2. судя по всему, после выполнения работы она должна быть каким-то образом "предъявлена" заказчику (в данном случае команде, т.к. работа выполняется для внутреннего проекта) для приемки, расчета по ней и закрытия как выполненной. Этого не произошло. Полагаю, можно и закрыть, но раз уж мы разбираем полет - выношу вопрос на обсуждение. Возможно, имеет смысл при назначении исполнителя назначать так же арбитра для разрешения споров. Например, @alecvert или кого-то из команды, например, @mparkhomenko или вообще кого-нибудь из внешних коллабораторов, типа @mklinkov или @githleo 

3. Если работа выполнена, полагаю не зависимо от схемы оплаты UTDEV должен быть перечислен на учетку исполнителя (не как раньше в день очередной выплаты (10/25)

4. Предлагаю для индикации просроченных задач использовать какой-то "горчичник", причем помнится лет 5 назад участвовал в проекте, где буквально лепились бумажки разного цвета - в зависимости от степени просрочки задачи.

**Comment by cptn-solo** [comment]
@matusdesign @RomaRAD приняты. 
Закрываю.

**Comment by cptn-solo** [comment]
@matusdesign не оправдал ни наших надежд, ни мы его, по всей видимости. Посему вакансия открыта, описание задачи корректирую под актуальные потребности. Результаты собеседований - в [исходную задачу по подбору](https://github.com/u-transnet/www-teaser/issues/16)

**Comment by cptn-solo** [comment]
Нет, все-таки закрываем вакансию. Остается @RomaRAD на фуллтайм

**Comment by cptn-solo** [comment]
@jackal1527 @alecvert 
Все-таки переоткрываем. Поток работ зашкаливает (см. [задачи с тегом art](https://github.com/u-transnet/www-teaser/issues?q=is%3Aopen+is%3Aissue+label%3Aart))
