### ISSUE TITLE
Рассмотреть вариант вывода токена на платформу NEO

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#29]
В дополнение к Bitshares можно рассмотреть вариант и процедуру вывода нашего токена на NEO, оценить трудозатраты, финансовые затраты, понять особенности сообщества и маркетинга в нем.

**Comment by kkrupovich** [comment]
тест @alecvert

**Comment by alecvert** [comment]
$NEO Projects

- HPB
- ElastOS @Elastos_org
- Ontology @OntologyNetwork
- NEX @neonexchange 
- Stokit TBA
- Qlink @QlinkMobi
- TheKey @thekeyvip
- Red Pulse @red_pulse_china
- DeepBrain TBA
- AlphaCat TBA
- PeerAtlas @PeerAtlas
- Universal Health Coin @UHCToken
