### ISSUE TITLE
[ВАКАНСИЯ] Автор текстов и презентаций (журналист, обозреватель)

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#33]
После обсуждения с @alecvert  фиксируем такой текст вакансии:

**Журналист / Редактор / Копирайтер в блокчейн-проект с перспективой роста**

Наша команда ищет талантливого журналиста для представления с точки зрения языка маркетинга и продвижения концепции, описания образа продукта для обычного пользователя, а также оперативное создание заметок, статей и т д постоянного всестороннего освещения процесса разработки и продвижения продукта во всех информационных полях.

**Чем предстоит заниматься:**

- готовить и размещать материалы от лица компании (статьи, анонсы, обзоры и т.п.) для различной целевой аудитории и по различным тематикам;
- быстро и эффективно создавать пресс-релизы по нашим требованиям;
- подбирать и контролировать работу удаленных авторов-копирайтеров;
-участвовать в разработке контент - стратегии компании.

**Что мы ждем от кандидата:**

- Умение работать с отрытыми задачами, анализировать проблему и находить элегантые решения. 
- успешный опыт написания статей, просьба предоставить примеры работ на различные тематики;
- отличные навыки письменного английского (обязательно); разговорный будет являться Вашим преимуществом;
- интерес к блокчейн-индустрии, готовность постоянно учиться и погружаться в процессы нашей блокчейн платформы;
- креативность и внимание к деталям;
- оперативность, ответственность и нацеленность на результат;
- грамотность;

**Плюсом будет:**

- успешная работа в СМИ и масс-медиа;
- знание рынка блокчейн-технологий и новых бизнес-моделей этой экономики (НЕ ICO, НЕ КРИПТОТРЕЙДИНГ, не переписывание статей и новостей, которые и так у всех на слуху);
- личный опыт в сфере блокчейн (использование криптовалют в личных целях);
- ведение своего блога продолжительное время.
- чувство юмора;
- вы умеренно сумасшедший за идею изменить мир к лучшему с помощью блокчейн;

**Примеры задач:**
- [Экономика блокчейна](https://github.com/u-transnet/info/issues/43)

**Comment by cptn-solo** [comment]
Собеседования тут #34

**Comment by alecvert** [comment]
@kkrupovich исправляю на свой манер

Журналист / Редактор / Копирайтер в блокчейн-проект

Наша команда ищет талантливого журналиста для корректировки с точки зрения языка маркетинга и продвижения концепции, описания образа продукта для обычного пользователя, а также формирование заметок и статей постоянного всестороннего освещения процесса разработки и продвижения продукта во всех информационных полях.

**Чем предстоит заниматься:**

-готовить и размещать материалы от лица компании (статьи, анонсы, обзоры и т.п.) для различной целевой аудитории и по различным тематикам;
- быстро и эффективно создавать пресс-релизы по нашим требованиям;
-подбирать и контролировать работу удаленных авторов-копирайтеров;
-участвовать в разработке контент - стратегии компании.

**Что мы ждем от кандидата:**

- успешный опыт написания статей на русском и английском языке , просьба предоставить примеры работ на различные тематики;
- отличные навыки письменного английского (обязательно); разговорный будет являться Вашим преимуществом;
- интерес к блокчейн-индустрии, готовность постоянно учиться и погружаться в процессы нашей блокчейн платформы;
- креативность и внимание к деталям;
- оперативность, ответственность и нацеленность на результат;

**Плюсом будет:**

- знание рынка блокчейн-технологий и новых бизнес-моделей этой экономики (НЕ ICO, НЕ КРИПТОТРЕЙДИНГ, не переписывание статей и новостей, которые и так у всех на слуху);
- личный опыт в сфере блокчейн (использование криптовалют в личных целях);
- ведение своего блога продолжительное время.
- чувство юмора;
- вы умеренно сумасшедший за идею изменить мир к лучшему с помощью блокчейн;
