### ISSUE TITLE
Иллюстративный материал, общая задача + частные по каждой иллюстрации/врезке

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#4]
Создаем задачи под врезки и иллюстрации.
Исходный документ пока [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit#heading=h.lh6n5a1simua), т.к. важно удобство комментирования и совместной работы. Потом переедет в wiki

@alecvert @iSergeevich коллеги, в этой задаче я в комментариях буду собирать места в исходном документе, для которых _уже понятна_ концепция иллюстративного материала, но вы можете предлагать в комментах тут свои варианты (в комментариях к гуглодоку есть кнопочка по которой можно вытащить ссыль на конкретный коммент и воткнуть его сюда, см. скрин где я беру ссылки на комменты)

<img width="666" alt="screen shot 2017-09-25 at 23 10 34" src="https://user-images.githubusercontent.com/1105555/30828598-d707ef50-a246-11e7-86a5-897cc5039735.png">

Потом я делаю из комментов к текущей общей задаче новые задачи и назначаю их исполнителю (пока это только Ваня). В рамках уже тех конкретных задач Исполнитель должен комментировать свои предложения с вложением изображений. В задачи (тикеты) и комментарии к ним можно добавлять картинки, все в курсе? см. скрин ниже, это доступно в процессе редактирования тикета/коммента.

<img width="709" alt="screen shot 2017-09-25 at 23 15 51" src="https://user-images.githubusercontent.com/1105555/30828811-86654358-a247-11e7-92da-a537569ecaab.png">

**Comment by cptn-solo** [comment]
Вставить в створ абзаца иллюстрацию "Реальная путевая структура, переходящая в цифровую"
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBM).
#5

**Comment by cptn-solo** [comment]
Вставить в створ абзаца поясняющую диаграму: 
общее пространство, внутри линии с кружками станций и "движущиеся" кружки подвижного состава. Можно добавить стиль из digitize with unity и изобразить передачу информации по путевой структуре (подводка к след. абзацу)
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBQ)
#6

**Comment by cptn-solo** [comment]
Поясняющая диаграма - фрагмент континента увеличен на фоне земного шара, покрытого схематичной паутиной путевой структуры. На увеличенном фрагменте - кружки подвижного состава "пересылают" токены станциям и путевой структуре. Путевая структура "подсвечивает" проложенный маршрут, выводя в выноске цифры объемов зарезервированных на маршрут ресурсов и каждая цифра снабжена пересчитанным в UTT значением (по аналогии с кросс-курсами) - это подводка к след. абзацу
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBU)
#7

**Comment by cptn-solo** [comment]
Этот абзац как раз можно проиллюстрировать "картой стратегического планирования инвестиций" - с зелеными, желтыми, красными областями
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBc)
#8

**Comment by cptn-solo** [comment]
Поясняющая диаграма - иерархическая структура затрат с балансами инфраструктурных активов
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBg)
#9

**Comment by cptn-solo** [comment]
Как это проиллюстрировать я не знаю. Вертится что-то простое, типа стопка монет, потраченных на аудит ДО и "открытая книга" ПОСЛЕ
Alec Vert
7:30 Сегодня
Иконка монет справа и иконка инструментов, стройки слева , иконки папок документации справа и типа соединяются все ок , палец вверх или successful или agreed
Весь коммент и обсуждение пока [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQCU), по вариантам картики - уже в задаче плз.

**Comment by cptn-solo** [comment]
Тут нужно что-то про сертификацию - штамп, сургучная печать, ОТК
[тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSVs9Ns)

**Comment by cptn-solo** [comment]
три разных типа "вагончиков" - три разных "тарифа" и станция, в которую входит три "маленьких", две "средних" и одна "большая" вагонетка
[тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQCo)

**Comment by cptn-solo** [comment]
краудфанд - толпа вкладчиков, представляющих разные социальные слои.
[тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSM0e_Q)

**Comment by cptn-solo** [comment]
"локальные" пространства, светящиеся огнями (функционирующие) и трещина в земной коре, разделяющая их
[тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSM0e_U)

**Comment by cptn-solo** [comment]
Иллюстрация: что-то про автономную транспортную систему, двоичный код (нолики и единицы) управляющий движением составов на карте-схеме ветвящихся транспортных путей. При этом важно как-то показать "экономическую составляющу" взаимодействия - т.е. эти нолики и единицы - это не только управляющие команды, но и экономические транзакции, сопровождающие перемещение ресурсов. 
коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSs0JKQ)
#10

**Comment by kkrupovich** [comment]
asdfasdfasd
