### ISSUE TITLE
Видеоролик на 1.5-2 минуты

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#42]
Это НЕ КЛИП. Привлекаем внимание не к исполнителю, а к сюжету, продукту:
- концентрированная воронка, затягивающая и дающая понимание
- иллюстрация к тому, что мы делаем
- показал - потом начинаешь комментировать (вебинар, конференция)

Сюжет
- глоссарий (начат [тут](https://github.com/u-transnet/info/wiki/Глоссарий))
- 1-2 страницы - что мы делаем, в чем продукт (создал задачу #44 )
- технологические уклады
- история развития
- синергия
- вход
- выход

Предлагаем поспорить, вступить в дискуссию, предлагая свои тезисы и решения.

По сути задача близка к "описанию сайта" - т.е. если взять сайт и описать его словами - получится как раз сюжет. Уже есть [задача](https://github.com/u-transnet/www-teaser/issues/61) на проработку текстов для сайта, т.о. @NYalinski может очень помочь в проработке сюжета для данного видео

- Это видео - "Часть 1" (intro)
- Вторая часть - это видео про [рождение uni-c](https://github.com/u-transnet/info/issues/17) ( #17 )

**Comment by cheredin** [comment]
В ролике основными понятиями выделил бы: демократия, децентрализация, открытость. 
И отдельно: универсальность. 
пока есть такая идея, немного сумбурно, но все же. 
Ролик примерно на 2 минуты. Каждая веха времени характеризуется своей цитатой какого-нибудь великого человека о демократии. Что значило это слово в античности, в средние века, в 18 веке (допустим), в 20 веке, и что значит сейчас. 
Эти цитаты приводят нас к тому, что значит "демократия" для нас. 
___
Эта идея без привязки к конечному продукту, потому что u-transnet делает "систему", а не приложение к какой-либо идее. 
И да, очень хорошо сказано в "Диктаторе" с Чарли Чаплин https://www.youtube.com/watch?v=fQqiUpy7dwE

**Comment by cptn-solo** [comment]
@cheredin спасибо за видос. Еще один могу бахнуть :) тоже без привязки - но в целом - тоже за децентрализацию и "демократию"
https://twitter.com/TeamSteemLive/status/943238415239270400

Но предлагаю на этом дискуссию здесь закончить, т.к. ИМХО в задаче вообще не сформулирована цель разработки ролика, и любые наши домыслы только усугубят проблему. 
PS: на ск. помню цель разработки была озвучена в созвоне, но никто не удосужился его тут отразить @alecvert @nat-brit

**Comment by icggithub** [comment]
Коллеги, высылаю предложение по структуре ролика. 
https://docs.google.com/document/d/1gGhh0-6upc_kdpSU6NZITPXkf9TIEkTSAPpv2CmRy1g/edit?usp=sharing
Просьба: ссылку на ролик "Буран" нигде и никому "наружу" не светить. Пользоваться только для личного просмотра. Жду встречные комментарии. Спасибо.
