### ISSUE TITLE
Координация работ по сайту и контенту

### ISSUE THREAD

**Issue by nat-brit** [u-transnet/info#45]
### Сайт:
- макет, шапка, цветовая схема, [верстка](https://github.com/u-transnet/www-teaser/issues/73), [содержание](https://github.com/u-transnet/www-teaser/issues/61).
### Контент: 
- сайт, видео, глоссарий, сведение концепции, тексты для презентаций.

**Comment by nat-brit** [comment]
BLOCK #22962292
TRANSFER |  
From | bkmfk
To | utd-pm
Quantity | 875.00000 UTDEV.SKILL
Работы до 29 декабря 2017

**Comment by nat-brit** [comment]
**По контенту:**
[Обзор документов на GitHub, полезные ссылки](https://docs.google.com/document/d/1y8a8kAjcawgG5EQ8szpiKSV_7Bi1jQ68j_E75f4g2DQ/edit)
[В концепцию](https://docs.google.com/document/d/1lCzMXEuHpWVg6STG4MXNfe1TM-t1gdjX_1a58geMh_Y/edit?usp=sharing)
[Тексты для сайта - логика, наброски](https://docs.google.com/document/d/1hAgcv3REB7H0T6E_Nx1eDO718lG49JmUla21ClTXtdY/edit?usp=sharing)

**[Закрытые задачи](https://github.com/u-transnet/www-teaser/issues?q=is%3Aissue+is%3Aclosed)**
[Шапка для сайта ](https://github.com/u-transnet/www-teaser/issues/71)
[Цветовая гамма сайта ](https://github.com/u-transnet/www-teaser/issues/72)
[По верстке](https://github.com/u-transnet/www-teaser/issues/74)

**В работе:**
Дизайн страницы "[Дорожной карты](https://github.com/u-transnet/www-teaser/issues/66)"
Дизайн "[оцифровка точек системы](https://github.com/u-transnet/www-teaser/issues/60)" и [иконки для карты](https://github.com/u-transnet/www-teaser/issues/55) 
Верстка для [мобильной](https://github.com/u-transnet/www-teaser/issues/75) и [десктоп-версии](https://github.com/u-transnet/www-teaser/issues/76) 
[Текстовое наполнение сайта](https://github.com/u-transnet/www-teaser/issues/61)  

**Идеи и наброски:**
[Концепция корпоративного сайта](https://github.com/u-transnet/www-teaser/issues/79) 
[Страница команды](https://github.com/u-transnet/www-teaser/issues/77) 
[Заготовки под Git, Facebook, VK, Twitter, Telegram, Medium](https://github.com/u-transnet/www-teaser/issues/38)

**Comment by cptn-solo** [comment]
@nat-brit 
BLOCK #23080122
CREATE PROPOSAL |  
Proposed operations | Transfer 875.00000 UTDEV from utd-pm to bkmfk
BLOCK #23080527
Active approvals to add | cptn-solo
BLOCK #23080518
Active approvals to add | arteg0r

Спасибо!
Надо формулировать следующую задачу и закидывать на нее скилл.
