### ISSUE TITLE
Координация работ по разработке движка и экономике платформы

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#46]
Потоки работ: 
- [алгоритмы](https://github.com/u-transnet/info/issues/2) распределения токена, стратегия размещения токенов направлений
- [шлюзы](https://github.com/u-transnet/codebase/issues/48), [движки](https://github.com/u-transnet/codebase/issues/43) распределения токена (бот + ERC20)
- [экономика](https://github.com/u-transnet/info/issues/47) токенов направлений - монетизация в целевом блокчейне
- концепция - координация [работы](https://github.com/u-transnet/info/issues/43) авторов (@cheredin @NYalinski )

**Comment by cptn-solo** [comment]
@alecvert скилл я сюда не закладываю, т.к. аванс до конца месяца уже выплачен и постфактум скилл смысла заводить нет. 
По факту задача в работе с 18 декабря, и будет основной до 29 декабря включительно. С нового года перехожу на пост-оплату, скилл запросил, просьба подтвердить транзакцию на учетке utd-architect:

CREATE PROPOSAL |  Proposed operations | Transfer 3,500.00000 UTDEV.SKILL from utd-architect to cptn-solo

**Comment by alecvert** [comment]
@kkrupovich подтвердил

**Comment by cptn-solo** [comment]
> [алгоритмы](https://github.com/u-transnet/info/issues/2) распределения токена, стратегия размещения токенов направлений

По алгоритмам ничего особо нового не добавилось, это по прежнему окна распределения, реализованные в виде ERC20 или бота-аукционера. Однако в процессе проработки экономики (см. ниже) стали более очевидны преимущества бота с точки зрения мотивации ранних инвесторов - похоже, спрос на базовый актив действительно будет подогреваться возможностью участия в эмиссии и продаже токенов новых направлений и адресных проектов ([подробнее](https://github.com/u-transnet/info/issues/47#issuecomment-354181757)) (например, инвесторы UTCORE смогут поучаствовать в эмиссии UTGAME)

> [шлюзы](https://github.com/u-transnet/codebase/issues/48), [движки](https://github.com/u-transnet/codebase/issues/43) распределения токена (бот + ERC20)

Проведены довольно глубокие исследования подходов к реализации мультиподписи в блокчейнах Graphene и Ethereum, в результате чего даже был изменен архитектурный проект нашего "кольцевого шлюза". Сейчас группа разработки склоняется к необходимости децентрализации хранения внешних активов и отказу от традиционной схемы с "общим кошельком". Судя по всему, единственным надежным способом аккумулирования внешних средств без централизации и доверия, является конверсия внешнего (BTC, ETH, BTS, etc.) актива в MPA-актив покупателем (выполняющим в данном сценарии роль шлюза) прямо в процессе совершения сделки. Возможно, единственно необходимым изменением стандартного движка графена будет создание нового типа объекта для обеспечения возможности хранения ссылки на "транзакцию обеспечения" во внешнем блокчейне, фиксирующую передачу внешней ценности (ETH, BTC) продавцом покупателю в обмен на MPA-актив, обеспеченный базовым активом блокчейна (UTT).
В рамках разработки шлюза в данный момент происходит подготовка докер-контейнера для запуска первых генезисов блокчейна (это даже не тест-нет, а скорее beta , которая в какой-то момент просто станет v1.0). Это в числе прочего означает и тот факт, что мы начинаем активно привлекать внешних заверителей в наш блокчейн, поскольку корректная реализация шлюза подобного рода невозможна без тестирования в условиях, максимально приближенных к "боевым". Если у кого-то есть сервер в кладовке (или лишних $100/мес. на аренду сервера в облаке) - welcome.

> [экономика](https://github.com/u-transnet/info/issues/47) токенов направлений - монетизация в целевом блокчейне

Постарался показать [принципы децентрализованного финансирования](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml), конверсию токенов направлений в UTT (там же) и [факторы роста UTT](https://github.com/u-transnet/info/issues/47#issuecomment-354181757)

> концепция - координация [работы](https://github.com/u-transnet/info/issues/43) авторов (@cheredin @NYalinski )

По концепции были надежды на @cheredin , но он по своему обыкновению тихо забил на нас (надеюсь, не на совсем, Илья, не стесняйся, возвращайся как будешь в силах). Отчасти, работой над концепцией можно считать моделирование децентрализованного финансирования, которое, по сути, прямо связана с моделью финансирования адресных проектов Заверителями в новой модели экономики U-Transnet (см. [альбом](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml), лист MPA-ECONOMY, диаграмма M6. Заверители Открытого Пространства TRANSNET (draft)). Теперь, если нам удастся организовать финансирование разработки путем выкупа UTDEV за ликвидные активы в рынке (у разработчиков), мы сможем проверить гипотезу финансирования, изложенную в [факторах роста UTT](https://docs.google.com/document/d/1umLovmsFU-E-ch3Gkd8GFJXB9NM4asBqqp7C_AYjhYY/edit?usp=sharing)  вконце пара абзацев.

Вообще в потоке работ по сайту сейчас довольно много делается для выстраивания какой-то целостной концепции нашего продукта - см. задачу @nat-brit #45 И это довольно приятно - атакуем концепцию уже с двух сторон. 

@Arteg0r ваш выход ;)) @nat-brit уже отчиталась ! Так на небольшой блог-обзор насобираем, @alecvert

**Comment by cptn-solo** [comment]
Следующий выпуск новостей ожидаем в #49
