### ISSUE TITLE
Сценарий монетизации токенов инфраструктурных направлений

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#47]
Проработать подход к децентрализации финансирования разработки платформы (UTCORE) и Игры (UTGAME):
- проработка регламента размещения инфраструктурных токенов платформы (UTCORE / UTGAME) в паре к UTDEV (включая ведение перечня допущенных к рынку учеток - whitelisting)
- утверждение механизма финансирования разработки путем выкупа ресурсных активов (UTDEV) внешними инвесторами в рынках DEX
- проработка сценариев монетизации инфраструктурных токенов платформы в целевом блокчейне (шлюз Bitshares - U-Transnet, расчеты потребности в UTT для обеспечения процедур распределения инфраструктурных токенов)

**Comment by cptn-solo** [comment]
> проработка регламента размещения инфраструктурных токенов платформы (UTCORE / UTGAME) в паре к UTDEV (включая ведение перечня допущенных к рынку учеток - whitelisting)

Готовлю диаграмму под регламент в бранче [models-mpa-economy-i1-i2](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml), по мере готовности буду сливать в мастер. Сам выкуп UTDEV и инвестирование его в UTCORE уже есть (i1)

> проработка сценариев монетизации инфраструктурных токенов платформы

см. лист "расчет транзита" в [книге](https://docs.google.com/spreadsheets/d/1IM2VzQZPyPGbC2dVHi5LKzZFDk9jeRN7BypVvfDEhdw/edit#gid=81548413) с оценкой влияния внешних держателей UTT

**Comment by cptn-solo** [comment]
@alecvert Прорисовал [i2](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml) (I2. Конвертация токенов направлений U-TECH в базовый актив U-TRANSNET (на примере UTCORE)), показал даже необходимость корректировки залоговой позиции UTCORE<UTT> заверителями по мере запроса расчета (settlement) держателями (инвесторами)  - но остается вопрос - каковы факторы, ведущие к росту стоимости UTT? Очевидно, это рост спроса при ограничении предложения - но с чем должен быть связан спрос на UTT в нашей модели? [рассуждения](https://docs.google.com/document/d/1umLovmsFU-E-ch3Gkd8GFJXB9NM4asBqqp7C_AYjhYY/edit?usp=sharing)

**Comment by cptn-solo** [comment]
@alecvert @nat-brit @Dima-Iron 
> но с чем должен быть связан спрос на UTT в нашей модели? рассуждения

Пока хочу оставить здесь явно оформившиеся за последние дни тезисы:
- в экономике TRANSNET SPACE и Bitshares есть два основных канала "эмиссии" базового актива:  
- - вознаграждение за блок (выплачивается/вестится активным заверителям, объем незначителен) и
- - worker (выплачивается/вестится инициатору направления/проекта, за воркер которого проголосовало сообщество)
- экономика TRANSNET SPACE предполагает расчет за услуги объектов, введенных в строй в результате реализации Адресных Проектов (АП), базовым активом блокчейна, либо производными от него (например, токеном данного адресного проекта, являющимся MPA-активом, эмитируемым под залог базового актива).
- после запуска АП в эксплуатацию, доступ к его услугам будут иметь только держатели базового актива в той или иной форме, поэтому спрос на базовый актив будет возрастать с запуском в эксплуатацию новых мощностей
**Вопросы:**
- ввиду того, что никаких других источников поступления базового актива в экономику нет, то  откуда будет браться UTT после того, как все воркеры остановятся, а все стейкхолдеры, желающие продать свой актив, уже это сделают?
- куда девается UTT, который пользователь вносит в качестве оплаты за услуги?

**Comment by nat-brit** [comment]
> в экономике TRANSNET SPACE и Bitshares есть два основных канала "эмиссии" базового актива...

А есть еще другие каналы? Какие?

> ввиду того, что никаких других источников поступления базового актива в экономику нет, то откуда будет браться UTT после того, как все воркеры остановятся, а все стейкхолдеры, желающие продать свой актив, уже это сделают?
- увеличить вознаграждение за блок заверителям при достижении некоего объема циркуляции UTT в зависимости от роста экономики? (если денег в экономике много, это плохо, но когда мало - тоже плохо, ведь есть какие-то формулы под это дело:)....  или выкуп у старых инвесторов (цена будет расти из-за возросшей потребности в нем), у них же будет приток уже как отдача от первых инвестиции? 
Привязать эмиссию токена к неким экономическим параметрам? Например, размер эмисси завист от скорости оборота токенов, стоимости активов, кол-ва активов и т.д. и т.п.?

> куда девается UTT, который пользователь вносит в качестве оплаты за услуги?

Распределяется согласно бизнес-плану (начинается окупаемость проекта).
@kkrupovich @alecvert

**Comment by cptn-solo** [comment]
@nat-brit 
> А есть еще другие каналы? Какие?

Это я образно. Впрочем, например, ютт мог достаться "по наследству" через положительный баланс учетки в генезисе блокчейна (форк)

> увеличить вознаграждение за блок заверителям при достижении некоего объема циркуляции UTT в зависимости от роста экономики? (если денег в экономике много, это плохо, но когда мало - тоже плохо, ведь есть какие-то формулы 

это первое, что приходит на ум, но это вызовет усиление централизации - ютт "вознесет" заверителей над всеми остальными участниками на недосягаемую высоту. 

> выкуп у старых инвесторов (цена будет расти из-за возросшей потребности в нем), у них же будет приток уже как отдача от первых инвестиции?

Во-первых, ранние инвесторы - держатели базового актива - вероятнее всего будут большой редкостью. 
Во-вторых, мы скорее рассматриваем предельный случай - когда уже никаких резервов в системе не осталось. 
Что касается отдачи инвестиций:
Рост курса ютта сам по себе является прибылью стейкхолдеров (всех держателей ютт) с полностью децентрализованным источником. У старых инвесторов приток будет так же в росте курса, а не результатом каких-то распределений с адресных проектов или токенов направлений.  В этом вся суть экономики Transnet Space - децентрализация, максимальное равновесие сил, не конкуренция, а сотрудничество в достижении общей цели. "Ровная тяга" - прямая аналогия с Bitcoin - там тоже ровное тиканье блоков и эмиссия очередных биткойнов каждые 10 минут предсказуемо ограничена, а вот спрос на сам биткойн - нет. И рост может принять действительно лавинообразный характер, если его не сдерживать буферными рынками - запуском новых направлений. При этом сам по себе момент наступления дефицита ютт-а будет означать принятие его ценности сообществом, а значит - выплаты воркеров подрядчикам станут возможны без посредничества инвестиционного капитала. 

> Привязать эмиссию токена к неким экономическим параметрам? Например, размер эмисси завист от скорости оборота токенов, стоимости активов, кол-ва активов и т.д. и т.п.?

Это можно устроить, но только если вознаграждение за блок устанавливать не символическим, а размером с печатный станок. Хотелось бы отказаться от использования заверителей в качестве печатного станка - для эмиссии у нас есть воркеры, а стейк заверителя складывается из стейка тех, кто его поддерживает.  Вопрос лишь в том, что должен оплачивать воркер, балансирующий отток ютт-а в резервный фонд (если предположить, что ютт, вносимый Пользователем в качестве "оплаты проезда" возвращается в резеврный фонд, а не Оператору АП. Почему не Оператору? Потому что воркер можно разголосовать, а оператор - это субъект со свободной волей, а значит, между пользователем и бизнесом нужен буфер, нейтральная территория - резервный фонд блокчейна).
Можно предположить, что воркеры адресных проектов , эксплуатирующихся в течение продолжительного времени, не будут прекращаться, т.к. постоянно будут участвовать в финансировании эксплуатационных расходов и всех циклов амортизации основных средств. Более того, объем воркера складывается именно из всех этих расходов, и является базой для расчета базовых тарифов на услуги Адресного Проекта - поскольку на этапе эксплуатации нет никаких промежуточных звеньев между пользователем объекта инфраструктуры, и подрядчиком, который участвует в строительстве или обслуживании объекта, то и "стоимость проезда" не может сильно отличаться от себестоимости хотя бы в силу законов социальной справедливости.

С другой стороны, возможно, вариант с Оператором АП, выступающим в роли "кассы" адресного проекта и принимающим оплату "за проезд" от пользоватлей, вполне подойдет каким-то из адресных проектов. При этом важно понимать, что это будут локальные рынки, рециркулирующие не только квалификационные и ресурсные активы, но и базовый актив блокчейна.
