### ISSUE TITLE
Перевод вакансии Fullstack web-разработчик 

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#48]
Переводим вакансию #37 на английский язык. 
Процесс в [**документе**](https://docs.google.com/document/d/1Om3VG7bc7inkAJaOH7goOI2HWcxK0E7KZp5woTx0o-A/edit?usp=sharing)

**Comment by cptn-solo** [comment]
@KozlovaMyr просьба заскилловать и дополнительно предлагаю результатом считать новую задачу/вакансию по образцу #37 но на английском языке с текстом, который готовится в документе из шапки

**Comment by KozlovaMyr** [comment]
BLOCK #23124707
TRANSFER 
From | mkmk940201
To | utd-content
Quantity | 25.00000 UTDEV.SKILL
смотрим 31 декабря

**Comment by cptn-solo** [comment]
Результат - задача #55 

@KozlovaMyr спасибо! @Arteg0r @nat-brit @alecvert у нас есть вакансия #37 (fullstack разработчик) на [английском](https://github.com/u-transnet/info/issues/55) языке. 

BLOCK #23511704
TRANSFER |  
From | utd-content
To | mkmk940201
Quantity | 25.00000 UTDEV
