### ISSUE TITLE
Координация работ по запуску пре-альфа генезисов блокчейна u-Transnet

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#49]
Предыдущий рапорт с мостика был тут #46 

Как бы нам этого ни хотелось, но все-таки откладывать запуск блокчейна смысла нет - нам нужно проверять кучу гипотез по воркерам, "майнингу" и шлюзам на доверии заверителям. 
Что хотелось бы получить, или хотя бы сформулировать задачи:
### Разработка
- Расширенный [набор скриптов](https://github.com/u-transnet/Gateway/issues/6) для узлов сети (заверителей) - котировки, потом подтверждения внешних транзакций - упакованный в докер для ноды заверителя - без базового набора MPA мы не стартанем экономику (@mparkhomenko дружище, нужен статус/созвон)
- Докер самой ноды - [готовый](https://github.com/u-transnet/codebase/issues/48#issuecomment-354419062) к развертыванию контейнер - подготовить понятную инструкцию (@mparkhomenko  тоже)
- [Поменять](https://github.com/u-transnet/utransnet-ui/projects/1?) что-нибудь в скине стандартного кошелька, чтобы отличался от Bitshares
### Управление продуктом
- Чат для заверителей, согласование схемы [i3](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml) Движение ценностей в процессе работы над проектом/направлением, анализ угроз
- Настройка и отладка механизма голосования за комитет и заверителей
- Настройка основного набора MPA-активов блокчейна
- Инструкции для создания залоговой позиции на ETH, RUR, USD, BTC
- Инструкции для подачи котировок (бот?)
- Очередной пересмотр конституции, включение туда пунктов про мастер-бранч генезиса блокчейна и про добровольность присоединения узлов сети к мастер-бранчу. 

Возможно, именно в таком виде - журнал проекта от лица лидеров направлений - и надо стартовать освещение работы тру блокчейнов, коллеги? 
@alecvert @Arteg0r @nat-brit @LastWarrior @bellevich 
Кому-то все-же лучше сводить эти журналы (план/факт + анализ) в блог проекта где-нибудь на медиуме/голосе

**Comment by cptn-solo** [comment]
@alecvert @Arteg0r @nat-brit 
BLOCK #23225798
TRANSFER |  
From | cptn-solo
To | utd-architect
Quantity | 350.00000 UTDEV.SKILL
До конца недели, 7 января включительно, возьму два дня, включая рисование i3

**Comment by alecvert** [comment]
@kkrupovich Возможно, именно в таком виде - журнал проекта от лица лидеров направлений - и надо стартовать освещение работы тру блокчейнов, коллеги? Да, но освещать нужно не только намерения , но и результаты. Преимущественно результаты. В начале каждого месяца/недели намерения на след. период времени, потом отчёт по результатам.

**Comment by cptn-solo** [comment]
@alecvert @nat-brit @Arteg0r 
> Да, но освещать нужно не только намерения , но и результаты. Преимущественно результаты

безусловно результаты

**Comment by nat-brit** [comment]
Результаты, которые хотелось бы получить за январь:
1. Запуск сайта-визитки, вкл. страницы с дорожной картой и концепцией, (вход в блокчейн - ??? тестовая страница с объяснением или записью на обучение (курс выходного дня для группы)) 
2. Готова концепция по корпоративному сайту
3. Готова концепция по блогу и соц.сетям, запущен канал в Телеграм 
4. Готов контент план на февраль-март
5. Развернут блокчейн на 5-10 нодах, тестим
6. Необходимо мнение специалистов по эконом. модели (?)
7. Концепция по видеороликам и согласованное ТЗ для первого ролика для сайта
8. Доработать идею по работе с пользователями: с сайта от кнопки "вход в блокчейн" - обучение (курс выходного дня 4-7 часов) - учетка в нашем блокчейне - получение токенов проекта - до полного понимания у пользователя внутренней экономики по обороту токенов внутри проекта.
9. По игре какие планы?

Что еще? Нужен созвон по плану на январь, февраль-март.
@kkrupovich @alecvert

**Comment by cptn-solo** [comment]
@alecvert @nat-brit @Arteg0r 
Результат, которого удалось пока добиться:

### Разработка

> Расширенный набор скриптов для узлов сети (заверителей) 

- cобрали [докер](https://github.com/u-transnet/Gateway/issues/6) для оптимизации процесса разработки скриптов, 
- подготовили [задачу](https://github.com/u-transnet/witness-scripts/issues/2) под разработку самих скриптов.

> Докер самой ноды - готовый к развертыванию контейнер 

- получил подтверждение от @mparkhomenko , что в ближайшие дни можно будет начинать тестирование запуска нод - по крайней мере, все компоненты уже были ранее отлажены

### Управление продуктом

> Чат для заверителей, согласование схемы i3 Движение ценностей в процессе работы над проектом/направлением, анализ угроз

- переименовали чат дизайна сайта в главный чат
- провели обсуждение [схемы i3](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml), в целом больших возражений пока не услышал, но возможно просто пока никто не рискнул полностью разобраться в этих диаграммах (i1-i3)

Остальные пункты плана пока остаются актуальными.

### Общие замечания

Основным результатом новогодних каникул стала проработка [диаграммы i3](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml), которая, по сути, является наиболее актуальной попыткой объединения процессов привлечения инвестиций и финансирования деятельности подрядчиков. Вместе с диаграммой родился еще один документ, описывающий экономику блокчейна - [рассуждения](https://docs.google.com/document/d/1umLovmsFU-E-ch3Gkd8GFJXB9NM4asBqqp7C_AYjhYY/edit?usp=sharing) (Монетизация токенов направлений U-TECH, стимулы роста UTT). В этот документ я очень настоятельно рекомендую заглянуть всем, кто интересуется экономикой нашего блокчейна. Уверен, что совместными усилиями мы сможем довести документ до ума. Так же рассчитываю на то, что после запуска сети бОльшая часть команды станет на шаг ближе к пониманию возможностей платформы Graphene и сможет принимать более активное участие как в разработке подобных документов, так и в донесении идей проекта до окружающих. 

По текущей задаче это, пожалуй, все, предлагаю рассчитать и сформулировать план на остаток текущей и следующую неделю ( #52 )

**Comment by cptn-solo** [comment]
@nat-brit @alecvert @Arteg0r 

> Результаты, которые хотелось бы получить за январь:
> Запуск сайта-визитки, вкл. страницы с дорожной картой и концепцией, (вход в блокчейн - ??? тестовая страница с объяснением или записью на обучение (курс выходного дня для группы))

про курсы обучающие услышал, надо будет создать задачу (возможно для @nat-brit) на проработку экономики токена таких курсов (запуск токена направления с последующим созданием рынка и выкупом за активы, обеспеченные UTT.

> Готова концепция по корпоративному сайту

Если под корпоративным сайтом мы понимаем приложение (кабинет) - то разве что концепцию можно успеть подготовить.

> Готова концепция по блогу и соц.сетям, запущен канал в Телеграм

Реально (@nat-brit ?)

> Готов контент план на февраль-март

Реально (@nat-brit ?)

> Развернут блокчейн на 5-10 нодах, тестим

Реально

> Необходимо мнение специалистов по эконом. модели (?)

Возможно, это было бы интересно, но предварительно надо понять - как донести до этих специалистов наше понимание модели?

> Концепция по видеороликам и согласованное ТЗ для первого ролика для сайта

Реально (@nat-brit ?)

> Доработать идею по работе с пользователями: с сайта от кнопки "вход в блокчейн" - обучение (курс выходного дня 4-7 часов) - учетка в нашем блокчейне - получение токенов проекта - до полного понимания у пользователя внутренней экономики по обороту токенов внутри проекта.

см. выше - я считаю это тянет на направление если не по объему финансирования, то по паттерну, который можно использовать из набора, доступного в нашей бизнес-модели (выпуск и продажа транзитного актива, возмещаемого в последствии базовым активом блокчейна).

> По игре какие планы?

@Arteg0r до конца месяца можешь что-то озвучить? 2 недели ближайшие. Мне тогда тоже надо что-то сочинить по этому поводу, кстати.

**Comment by nat-brit** [comment]
Нужен созвон по всем пунктам:)

**Comment by cptn-solo** [comment]
@nat-brit @alecvert @Arteg0r , если принципиальных возражений нет, просьба выловить и подтвердить возмещение по этой задаче на учетке utd-architect:
BLOCK #23467328
CREATE PROPOSAL |  Review period begin | — Expiration time | January 13, 2018, 12:09:57 PM
Proposed operations | Transfer 350.00000 UTDEV from utd-architect to cptn-solo

BLOCK #23467701
UPDATE PROPOSAL |  Fee paying account | cptn-solo
Active approvals to add | cptn-solo

BLOCK #23467677
UPDATE PROPOSAL |  Fee paying account | arteg0r
Active approvals to add | arteg0r

**Comment by Arteg0r** [comment]
@kkrupovich @nat-brit 
> @Arteg0r до конца месяца можешь что-то озвучить? 2 недели ближайшие. Мне тогда тоже надо что-то сочинить по этому поводу, кстати.

Озвучу в понедельник план до конца месяца. Тогда же его и обсудим.

**Comment by alecvert** [comment]
@kkrupovich 
![image](https://user-images.githubusercontent.com/30151576/34869883-3af06e58-f7aa-11e7-8536-885129e5dc98.png)
не стоит такое в отчёт писать)

> провели обсуждение схемы i3, в целом больших возражений пока не услышал, но возможно просто пока никто не рискнул полностью разобраться в этих диаграммах (i1-i3)"

будем продолжать штурмовать

+
Пора заводить акк на медиуме, если нет и писать как технический лидер проекта, см. те отчёты , которые я сбрасывал в телеграмм. Причём, я думаю, что с переводом на англ, это будет переводить переводчик.

**Comment by alecvert** [comment]
> Запуск сайта-визитки, вкл. страницы с дорожной картой и концепцией, (вход в блокчейн - ??? > тестовая страница с объяснением или записью на обучение (курс выходного дня для группы))

Текстовую страницу с объяснением или записью на обучение успеем подготовить? Это по сути новый лэндинг. 

> Готова концепция по корпоративному сайту

Корпоративный сайт или App ?

> Готова концепция по блогу и соц.сетям, запущен канал в Телеграм

Телегу думаю, что пока не надо, Февраль-март.
Соц. сети после запуска сайта.
Блог на медиуме можно вести на рус. и англ. уже сейчас. Это наша история помимо гитхаба. Это нужно было сделать уже давно.

> Готов контент план на февраль-март

Контент план внутренний или внешний (СМИ и т д)?

> Необходимо мнение специалистов по эконом. модели (?)

Да, 100% думаю тут надо привлекать адвайсеров. Может Марию с Киберфонда , если она понимает экономику, ну или других людей.

Мнение адвайсеров должны попадать в инфо поля.

**Comment by cptn-solo** [comment]
@alecvert 
> Мнение адвайсеров должны попадать в инфо поля.

Это палка о двух концах, коллега.
