### ISSUE TITLE
Иллюстрация: Реальная путевая структура, переходящая в цифровую

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#5]
Вставить в створ абзаца иллюстрацию "Реальная путевая структура, переходящая в цифровую"
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBM).

**Comment by iSergeevich** [comment]
эскиз 
![img_20170928_221946](https://user-images.githubusercontent.com/31988874/30980709-6593fe48-a49b-11e7-97ba-cdfa7ada80e8.jpg)

**Comment by cptn-solo** [comment]
@iSergeevich это норм идея в том смысле, что реальная слева, цифровая справа (даже про "наши койны" хорошая мысль, хоть ты и немного не правильно интерпретировал нашу идею койна ;), но ИМХО это немного глубже, чем нам надо для иллюстрации. Имелась ввиду ваша с @alecvert концепция "оцифровки", которую ты реализовал в прототипе лого с буквой U - половина реальная, половина "проволочная". 
Можешь попробовать сделать схематичную путевую структуру (было в одной из задач по-моему, там где я про "шарики говорил" - схема из линий и кружков на ней), а не изображение "реальной" путевой структуры? И вот эту "схему" оцифровать?

**Comment by iSergeevich** [comment]
да смогу. завтра

**Comment by alecvert** [comment]
@iSergeevich где?

**Comment by iSergeevich** [comment]
новые иконки, новая графика
![default](https://user-images.githubusercontent.com/31988874/31497873-bb5314a2-af79-11e7-9f6d-e2ae6f42377e.png)

**Comment by iSergeevich** [comment]
![2](https://user-images.githubusercontent.com/31988874/31623563-3cbb1840-b2b9-11e7-8143-cf2939f8ff94.png)
с расшифрованными иконками и исправленной графикой по отношению к верхнему эскизу

**Comment by iSergeevich** [comment]
![3](https://user-images.githubusercontent.com/31988874/31647484-eebcbe3c-b321-11e7-877b-a1ffc878b0b5.png)

**Comment by cptn-solo** [comment]
Схема справа - набор клипарта, не имеющего отношения к теме вообще. просто какие-то символы. 
На самом деле то, что @iSergeevich совместил этот слайд с другим (левая часть приехала из другой задачи, очевидно) - и на этом левом слайде _уже есть_ отображение цифровой структуры (нижняя пунктирная линия -  это и есть информационные потоки, блокчейн, оцифрованный транснет) - то не понятно зачем вообще правая часть.

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich надо обсуждать голосом. Пока из иллюстраций устраивает вот эта https://user-images.githubusercontent.com/31988874/31635209-68533c50-b2df-11e7-94a0-a1e7603267bd.jpg
