### ISSUE TITLE
Координация работ по контенту, 

### ISSUE THREAD

**Issue by nat-brit** [u-transnet/info#50]
**По контенту:**
По контенту из [прошлой](https://github.com/u-transnet/info/issues/45)
[Обзор документов на GitHub, полезные ссылки](https://docs.google.com/document/d/1y8a8kAjcawgG5EQ8szpiKSV_7Bi1jQ68j_E75f4g2DQ/edit)
[В концепцию](https://docs.google.com/document/d/1lCzMXEuHpWVg6STG4MXNfe1TM-t1gdjX_1a58geMh_Y/edit?usp=sharing)
[Тексты для сайта - логика, наброски](https://docs.google.com/document/d/1YVSPuuhYEkJnb-Y-H7ADx6Qv96yKYGDDnarQ0iPUoXg/edit#) @jackal1527 @alecvert 

**В работе:**
Дизайн страницы "[Дорожной карты](https://github.com/u-transnet/www-teaser/issues/66)"
Дизайн "[оцифровка точек системы](https://github.com/u-transnet/www-teaser/issues/60)" и [иконки для карты](https://github.com/u-transnet/www-teaser/issues/55) 
Верстка для [мобильной](https://github.com/u-transnet/www-teaser/issues/75) и [десктоп-версии](https://github.com/u-transnet/www-teaser/issues/76) 
[Текстовое наполнение сайта](https://github.com/u-transnet/www-teaser/issues/61)  
[По презентации по токенизации адресных проектов, движение активов в процессе финансирования, строительства и эксплуатации #23](
https://github.com/u-transnet/info/issues/23)
[Экономика блокчейна u-transnet #43](https://github.com/u-transnet/info/issues/43)
[Сценарий монетизации токенов инфраструктурных направлений #47](https://github.com/u-transnet/info/issues/47) [Иллюстрации]( https://github.com/u-transnet/info/issues/10)
[Модификация стратегии размещения - сведение в документ результатов 3-ей итерации #40](https://github.com/u-transnet/info/issues/40)

[Текст описания продукта под задачу разработки видеоролика #44](https://github.com/u-transnet/info/issues/44) + [задача 42](https://github.com/u-transnet/info/issues/42) и [задача 17](https://github.com/u-transnet/info/issues/17)

**Идеи и наброски:**
[Концепция корпоративного сайта](https://github.com/u-transnet/www-teaser/issues/79) 
[Страница команды](https://github.com/u-transnet/www-teaser/issues/77) 
[Заготовки под Git, Facebook, VK, Twitter, Telegram, Medium](https://github.com/u-transnet/www-teaser/issues/38) 
Вакансии: [Автор, редактор, обозреватель](https://github.com/u-transnet/info/issues/34)

**Участие** в [работах по запуску пре-альфа генезисов блокчейна u-Transnet #49](https://github.com/u-transnet/info/issues/49)

**Comment by nat-brit** [comment]
Block #23240273
From | bkmfk
To | utd-pm
Quantity | 1,400.00000 UTDEV.SKILL
До конца следующей недели 12 января включительно (всего 8 дней)
@kkrupovich  @alecvert @Arteg0r

**Comment by cptn-solo** [comment]
@nat-brit создал для @Dima-Iron задачу #51 , просьба рассмотреть возможность создания (с участием и помощью со стороны исполнителя и, возможно, с моей) еще двух задач на следующие 2 недели (можно заняться этим в понедельник по результатам #51 ): 
- токенизация + экономика (предположительно выполнение на неделе 15-19 января)
- завершена структура сайта, включая дорожную карту (предположительно выполнение на неделе 22-26 января)

**Comment by nat-brit** [comment]
Отчет по 12 января и планы на ближайшую неделю 15-19 января.

1. **Сайт-визитка:**

- Практически закончили логику и тексты на [главную](https://docs.google.com/document/d/1yV0gj_Api5i7j1EXlf6xAfo8QiQFeDB1KzJ4ivo14Iw/edit), 
- Сформировать задачи по внешнему виду и наполнению страниц (@kkrupovich @alecvert @Dima-Iron @jackal1527 ), предлагаю запланировать созвон во вторник:
1. - по экономике и токенизации 
3. - по Дорожной Карте
4. - страница команды
5. - по модификации макета сайта 
6. - задачи переводчику

2. **Презентации** (@alecvert @RomaRAD @jackal1527)
Сформулировать задачу по картинке для презентации в АЭ, согласуется с задачей[ 23](https://github.com/u-transnet/info/issues/23): презентация по токенизации адресных проектов, движение активов в процессе финансирования, строительства и эксплуатации

3. **Запуск блокчейна**
Задачи сформулированы [тут](https://github.com/u-transnet/info/issues/52)

4. **Концепция по видеороликам и согласованное ТЗ для первого ролика для сайта** - сначала согласовать все страницы сайта и потом сделаем ТЗ по видеоролику - задача на эту неделю (см. #44 + задача 42 и задача 17) (@alecvert @Dima-Iron)

5. **Обсуждение экономики и токенизации (Развиваем размышления и i3)**
План созвонов на неделю? Участники обсуждения?
Необходимо мнение сторонних специалистов. К кому обращаемся за консультацией?
Предлагаю организовать созвон на понедельник или вторник (@kkrupovich @alecvert )

6. **Вакансии:** 
- @Dima-Iron приступил к работе, созвон с еще одним кондидатом (вакансия: автор, редактор, обозреватель) завтра 15/01)
- Поиск геймдизайнера - [задача](https://github.com/u-transnet/info/issues/53) в работе @Arteg0r 
- Поиск кондидатов на ядро, фронт, бэк, архитектор/PM для kit 
- Сделать обновленную доску по вакансиям 

**В отношении планов на январь-февраль:**
**Сайт-визитка**
Запуск сайта-визитки, вкл. страницы с дорожной картой и концепцией, (вход в блокчейн - ??? тестовая страница с объяснением или записью на обучение (курс выходного дня для группы))- думаю, сделаем основное, успеем ли сделать регистрацию в блокчейн для пользователей @kkrupovich?
**Соц.сети**
Запуск блога в Medium - к концу января,
Запуск канала в Τelegram - после выхода сайта, на начало февраля. Нужен человек, который будет отвечать за ведение канала.
Нужен специалист по пиару (составление медиа-плана - первичная задача)
Концепция по соц.сетям прорисовывается, к концу января будет полное понимание по запуску.
**Корпоративный сайт**
Концепция по корпоративному сайту превращается в задачу по модификации сайта-визитки + разработке мобильного приложения для пользователей блокчейна (задача на февраль?)
**Обучение**
Про курсы обучающие надо будет создать задачу  на проработку экономики токена таких курсов (запуск токена направления с последующим созданием рынка и выкупом за активы, обеспеченные UTT) - не ранее февраля
**Игра**
По игре задачи прописаны [тут,](https://github.com/u-transnet/Gamedev/issues/3) @Arteg0r в понедельник 15/01 озвучит подробнее. Нужно ли добавить информацию по этому направлению на сайт-визитку?

BLOCK #23556394
bkmfk
To | utd-pm
Quantity | 875.00000 UTDEV.SKILL
Период с 15.01.2017-19.01.2017 включительно.

**Comment by cptn-solo** [comment]
@nat-brit 
> Сформулировать задачу по картинке для презентации в АЭ, согласуется с задачей 23: 

@alecvert  уже создал [задачу про Арабский мир](https://github.com/u-transnet/www-teaser/issues/88) - вы об одном и том же говорите? или это разные по назначению заказы - один для презентации, другой для сайта?

>  успеем ли сделать регистрацию в блокчейн для пользователей 

можно регистрировать хоть сейчас - вопрос лишь в том, что изменения экономики целевого блокчейне, будет вноситься в уведомительном порядке -  вероятно, нужно сразу предусмотреть разработку регламента формирования генезис-файлов для ветки кода U-Transnet, администрируемой командой U-TECH. С другой стороны, у нас нет особо срочных поводов для хардфорка (если только не появится что-то критичное в upstream , затрагивающее и наш проект), а потому я думаю, что регистрация в блокчейне, можно сказать, вопрос решенный. По мере появления первых заверителей будет согласован генезис-файл для базовой версии u-transnet , и в какой-то момент осуществлен форк на этот генезис.

> Нужно ли добавить информацию по этому направлению на сайт-визитку? (про Игру)

Мое мнение - это скорее запись в блоге, чем ссылка из главного сценария (сайт - как сценарий использования Transnet Space). Я бы подумал над блогом игрового направления - и сослался из блогов u-tech/ut-dev

> Сделать обновленную доску по вакансиям

У всех это есть в планах на неделю :))) надо как-то скоординироваться

**Comment by nat-brit** [comment]
Да, задачи по арабскому миру и по доске с вакансиями - это именно задачи #88 и [эта доска](https://github.com/u-transnet/info/projects/4).
Игру тогда на главную страницу сайта пока не добавляем, про блог игрового направления - идея хорошая. Принято.
Если ни у кого вопросов по предыдущему периоду нет, предлагаю его закрыть и приступить к следующему: с 15 по 19 января включительно.

**Comment by cptn-solo** [comment]
@nat-brit 

> Если ни у кого вопросов по предыдущему периоду нет, предлагаю его закрыть 

@nat-brit @alecvert @Arteg0r коллеги, предлагаю подтвердить транзакцию на учетке **utd-pm**

BLOCK #23556527
CREATE PROPOSAL |  Proposed operations | Transfer 1,400.00000 UTDEV from utd-pm to bkmfk

BLOCK #23559717
UPDATE PROPOSAL |  Fee paying account | cptn-solo
Active approvals to add | cptn-solo

BLOCK #23559551
UPDATE PROPOSAL |  Fee paying account | bkmfk
Active approvals to add | bkmfk

**Comment by nat-brit** [comment]
Закрываем эту неделю с такими результатами:

На текущий момент:
**1. Сайт-визитка:**
- Макет сайта опять меняется. [Промежуточные варианты тут](https://github.com/u-transnet/www-teaser/issues/91), дизайн [шапки тут](https://github.com/u-transnet/www-teaser/issues/90).
- Готов [текст для страницы по токенизации](https://docs.google.com/document/d/1Bm8wfnKCT4xDGIV9l8UB1Hx40C6XYH3oK6XLycS1OJQ/edit), осталось доработать диаграмму.
- [Драфт ](https://docs.google.com/document/d/1RYW539VZRiQn3jnMuGkKvbW2UB2up15sH3m_ZvLBKTM/edit)для дорожной карты - задача на следующую неделю.
- Разделы сайта - О проекте, Концепция, Токенизация, Дорожная карта, Моделирование (игра), Партнеры, Команда, Блог, Регистрация, FAQ - обсуждаются.
- Задачу **Концепция по видеороликам** - отложили, пока рано (см. #44 + задача #42 и задача #17) 

**2. Презентация в АЭ** - принят [этот вариант](https://github.com/u-transnet/www-teaser/issues/88)

**3. Запуск блокчейна**: запущен!!!:) Текущие [задачи тут](https://github.com/u-transnet/info/issues/52). Идет работа над [реф.кошельком Bitshares](https://github.com/u-transnet/utransnet-ui/projects/1) и кастомизацией интерфейса. .

**4. Экономика и токенизация**

- Понимание **[по экономике](https://github.com/u-transnet/info/issues/47#issuecomment-358157700)** вроде складывается, по крайней мере, есть, что тестировать:))) 
- Механика  обмена токенами в работе [тут](https://github.com/u-transnet/info/issues/52)
- Симулятор TRANSNET -[Программный прототип. Архитектура решения](https://docs.google.com/document/d/1u2sPJNCBUANPfdsEjJ6MSofIQ3VsHTOylfVS7iTYUaM/edit), [Альбом диаграмм](https://www.draw.io/#Hu-transnet%2Ftransnet-simulator%2Fconcept%2Fconcept%2Fdrawings%2Fut-simulator.xml)

**7. Игровое направление:** продолжаем обсуждать концепцию, требования к прототипу и пр. Подробности [тут](https://docs.google.com/document/d/11Sk2VMlI0M9kjpFsFv1ZITH34eyoFcKSbHnLl5fOxFE/edit).

**5. По вакансиям**:  пополнение @codename-art и@netral23 в команде разработчиков:)  есть хорошие кандидаты на вакансии "автора-обозревателя" и "по соц.сетям (готовы приступить к работе). Очередь на собеседования на вакансию [ведущего геймдизайнера](https://github.com/u-transnet/info/issues/53), что не может не радовать:) Продолжаем поиск [системного аналитика, архитектора](https://github.com/u-transnet/info/issues/31).

**6. Задача “обновленная доска по вакансиям #20** переросла в новые задачи “[Навести порядок на Гитхабе](https://github.com/u-transnet/info/issues/58) и[ Интеграция Гитхаба с другим удобоваримым сервисом](https://github.com/u-transnet/info/issues/59).

Ждем хорошие новости из АЭ:)

20/01/2018
@kkrupovich @alecvert @Arteg0r 

Если ни у кого вопросов по предыдущему периоду нет, предлагаю его закрыть.

**Comment by cptn-solo** [comment]
@nat-brit 

> 3. Запуск блокчейна: запущен!!!:) Текущие задачи тут. Идет работа над реф.кошельком Bitshares и кастомизацией интерфейса. 

Он давно запущен :) но один узел - это не сеть. Хочется запустить именно узлы заверителей блокчейна, сформировать первый круг доверия нового DAC на Graphene, и двигаться дальше именно в этом формате.

> Идет работа над реф.кошельком Bitshares и кастомизацией интерфейса. 

тут важен порядок слов - идет работа над кастомизацией интерфейса (форк референтного кошелька Bitshares) с целью ребрендинга под символику U-Tech, как это делается в каждом новом форке реф. кошелька биржами, обменниками и другими подобными проектами поверх Bitshares. Но в нашем случае есть одно ключевое отличие - для нас форк реф.кошелька Bitshares является внутренним инструментом для стейкхолдеров, не желающих ждать появления новых, специализированных интерфейсов U-TRANSNET в рамках Transnet Space. Кроме того, как я [упоминал](https://github.com/u-transnet/utransnet-ui/projects) ранее, команда разработки будет стараться по возможности поддерживать совместимость референтного интерфейса с новым блокчейном (и API к нему) по очень простой причине - этот интерфейс организован таким образом, что хорошо поддерживает расширение и изменение набора модулей и блоков. Если с движком GUI (он довольно старый) не будет проблем - реф.кошелек лишь изменит состав модулей и будет доступен "любителям" в привычном исполнении.

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert 

> Если ни у кого вопросов по предыдущему периоду нет, предлагаю его закрыть.

Коллеги, если ни у кого нет возражений - просьба подтвердить транзакцию на учетке **utd-pm** :

BLOCK #23765576

CREATE PROPOSAL |  
-- | --
Review period begin | —
Expiration time | January 23, 2018, 10:02:29 PM
Proposed operations | Transfer 875.00000 UTDEV from utd-pm to bkmfk

**Comment by cptn-solo** [comment]
@nat-brit 

UPDATE PROPOSAL |  
-- | --
Fee paying account | cptn-solo
Proposal object id | 1.10.7856
Active approvals to add | cptn-solo


UPDATE PROPOSAL |  
-- | --
Fee paying account | bkmfk
Proposal object id | 1.10.7856
Active approvals to add | bkmfk
