### ISSUE TITLE
Логическое и текстовое наполнение стартовой страницы сайта transnet.tech

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#51]
В рамках #50 начата разработка [документа](https://docs.google.com/document/d/1YVSPuuhYEkJnb-Y-H7ADx6Qv96yKYGDDnarQ0iPUoXg/edit#), являющегося описанием всех блоков и текстов стартовой страницы сайта  transnet.tech. Документ необходим для использования в качестве отправной точки для модификации текущего макета полноразмерной версии сайта transnet.tech коллегами (@jackal1527 и @EvgeniyPolyakov)

@Dima-Iron @nat-brit коллеги, будем ли в рамках этой задачи делать локализацию, или позже поставим задачу переводчику? Предлагаю второе.

Просьба оценить/скорректировать формулировку задачи и оценить трудозатраты (предварительно обсуждали завершение к вечеру понедельника, 15 января, 5 дней с учетом ранее проделанной работы)

**Comment by Dima-Iron** [comment]
BLOCK #23449133
TRANSFER 
Operation ID 
From | dima-iron
To | utd-content
Quantity | 175.00000 UTDEV.SKILL

смотрим в понедельник, 15 января 2018

**Comment by nat-brit** [comment]
Задачу переводчику позже. По времени на работу с текстом получилось больше, пересчитаем по факту приемки задачи. Вот последний [вариант](https://docs.google.com/document/d/1yV0gj_Api5i7j1EXlf6xAfo8QiQFeDB1KzJ4ivo14Iw/edit), к понедельнику как договаривались будет закончен. Картинки, если честно, не очень ложатся. Надо додумать с оформлением. @kkrupovich @alecvert

**Comment by cptn-solo** [comment]
@Dima-Iron @nat-brit @alecvert результат уходит в работу в [задачу переработки главной страницы](https://github.com/u-transnet/www-teaser/issues/89)
Текущую закрываем

BLOCK #23554978
TRANSFER |  
From | utd-content
To | dima-iron
Quantity | 175.00000 UTDEV

Спасибо!
