### ISSUE TITLE
Координация запуска (продолжение) + экономика блокчейна

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#52]
Предыдущий отчет #49 

Продолжаем готовить запуск, параллельно работаем над экономикой и документацией. 

### Управление разработкой

- Вакансии (ядро, фронт, бэк, архитектор/PM для kit) - вообще - актуализировать [доску](https://github.com/u-transnet/info/projects/4?) по вакансиям совместно с @Arteg0r и @nat-brit 
- обозначить курс на приведение конфигурации продукта к open source best practices ([например](https://opensource.guide/starting-a-project/), или [вот](https://hackernoon.com/i-thought-i-understood-open-source-i-was-wrong-cf54999c097b)) - возможно, внести изменения в вакансии - обозначить Open Source в качестве бонуса хотя бы.
- продолжаем [анализ](https://github.com/u-transnet/Gateway/issues/5) и проектирование [шлюзов](https://github.com/u-transnet/Gateway/projects/2?) и [движка распределения](https://github.com/u-transnet/codebase/projects/4?)

### Запуск блокчейна

- Настройка и отладка механизма голосования за комитет и заверителей
- Настройка основного набора MPA-активов блокчейна
- Инструкции для создания залоговой позиции на ETH, RUR, USD, BTC
- Инструкции для подачи котировок (бот?)
- Пересмотр конституции, включение туда пунктов про мастер-бранч генезиса блокчейна и про добровольность присоединения узлов сети к мастер-бранчу.

### Экономика 

- Развиваем [размышления](https://docs.google.com/document/d/1umLovmsFU-E-ch3Gkd8GFJXB9NM4asBqqp7C_AYjhYY/edit?usp=sharing) и [i3](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml)
- ~~Совместно с @Dima-Iron и @nat-brit ставим задачу @Dima-Iron (и меня в качестве консультанта) на разработку документа, упомянутого в #50 ([тут](https://github.com/u-transnet/info/issues/50#issuecomment-356974070))~~

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert фактически работаю по этому плану начиная с четверга, 11 января, и контрольной датой предлагаю считать пятницу, 19 января 2018 (7 дней, 175скилл/день).

BLOCK #23513300
TRANSFER |  From | cptn-solo
To | utd-architect 
Quantity | 1,225.00000 UTDEV.SKILL

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert
Хотел бы подвести промежуточные итоги за первую (короткую) послепраздничную неделю. 
Как я уже отмечал ранее в #49 , основные усилия я сейчас концентрирую на проработке вопросов монетизации токенов направлений, децентрализации финансирования, запуску блокчейна u-Transnet. Особо хотелось бы отметить, что первая неделя 2018 была отмечена любопытным событием - о реализациии Atomic swap заявил еще один проект - scorum (первым был decred). Об этом я уже [упомянул](https://github.com/u-transnet/Gateway/issues/5#issuecomment-357266524) в задаче по проработке вопроса атомарных свопов для движка нашего блокчейна, и хочу отметить, что слежу за развитием ситуации вокруг scorum и decred весьма внимательно. 
Кроме того, после периода автономной разработки модели размещения и децентрализованного финансирования, нам удалось несколько раз провести обсуждение i1-i3 и теперь ни у кого не возникает сомнений в том, что есть смысл поднять блокчейн и продолжать проверку гипотез i1-i3 уже непосредственно в процессе функционирования DAC 
(to be continued)

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert  

> **Разработка:** продолжаем анализ и проектирование шлюзов и движка распределения

В сегодняшних бурных обсуждениях (понедельник) Игры и изменения подхода к подаче информации на стартовой странице сайта мы почти не заметили начало диалога между командой Bitshares и Scorum на предмет портирования реализации Atomic swaps.

> **Запуск блокчейна:** подготовка 

С прошлой итерации ( #49 ) оставался вопрос 
> докер ноды для заверителей
 
теперь это [задача](https://github.com/u-transnet/codebase/issues/28) со скилом @mparkhomenko  на завтра. 
Кроме того, был вопрос о ребрендинге референтного кошелька под проект u-tech - сейчас у нас репозиторий utransnet-ui является прямым потомком bitshares-ui со всей символикой родительского проекта:

> Поменять что-нибудь в скине стандартного кошелька, чтобы отличался от Bitshares

Пока макет сайта проходит итерацию изменения, у нас есть возможность использовать ресурсы в другом потоке работ - и @EvgeniyPolyakov предложил нам свои услуги для проведения небольших (пока) косметических изменений в интерфейсе кошелька u-transnet - доска проекта [тут](https://github.com/u-transnet/utransnet-ui/projects/1), мы с @EvgeniyPolyakov (и, желательно, другими участниками команды) будем ее пополнять и создавать по ней задачи на кастомизацию UI. В перспективе опыт сборки и развертывания среды разработки UI нам пригодится как для реализации своих собственных интерфейсов, так и для разработки, например, шлюзов в Bitshares и в нашем собственном форке исходной версии кошелька - мы собираемся поддерживать совместимость нашего блокчейна с базовым интерфейсом до тех пор, пока собственный интерфейс не станет популярнее базового.

> **Экономика:** Совместно с @Dima-Iron и @nat-brit ставим задачу @Dima-Iron (и меня в качестве консультанта) на разработку документа, упомянутого в #50 (тут)

Совместными усилиями с коллегами пришли к выводу, что для сайта сейчас нам нужно описание токенизации, а не экономики токена, которая пойдет в работу позже. [Задача](https://github.com/u-transnet/info/issues/56) #56 

(to be continued)

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert

> **Экономика:** Развиваем размышления и i3

Очередной [шаг вперед](https://github.com/u-transnet/info/issues/47#issuecomment-358157700), ~~два шага назад~~ в вопросе монетизации токена направления и экономики блокчейна в целом. Пора начинать рисовать ведра, или сепараторы @LastWarrior 

> Вакансии (ядро, фронт, бэк, архитектор/PM для kit) 

В нашей команде пополнение, @codename-art  [full stack web dev](https://github.com/u-transnet/info/issues/38#issuecomment-358090501) , и мы с коллегой договорились возобновить работы над [симулятором](https://github.com/u-transnet/transnet-simulator), а поскольку интерфейсы симулятора являются по сути интерфейсами оперативного режима [Игры](https://github.com/u-transnet/GameOpMode) - фактически это можно считать началом разработки и в игровом направлении тоже. 
Остается все же сконцентрировать усилия на запуске направления UTKIT (аппаратный прототип) - поиске [Архитектора](https://github.com/u-transnet/info/issues/31), который смог бы поставить задачу на проектирование аппаратного (технологического) прототипа, а возможно - и возглавить это направление исследований и разработки команды U-TECH. 

> продолжаем анализ и проектирование шлюзов и движка распределения

Со стороны шлюзов и скриптов у нас пока пауза, поскольку @mparkhomenko переключился на [задачи](https://github.com/u-transnet/codebase/issues/28), связанные с запуском блокчейна, а @UspenskyDritry пока задачи в работу не берет. Но есть и хорошая новость - на днях я общался с потенциальным кандидатом на задачи по шлюзам, который имеет опыт работы в данной области. Если наш контакт по каким-либо причинам не прервется - работы над шлюзами возобновятся в начале 20х чисел января.

Другая приятная новость - @mparkhomenko и @EvgeniyPolyakov [починили](https://github.com/u-transnet/transnet.tech/issues/2) CORS при запросе номера блока, выполняемого сайтом с домена transnet.tech на метод API, развернутый в домене transnet.space . Так что на dev уже тикают блоки u-transnet. Цепь ждет своих заверителей ;) Звучит зловеще ;)))

(to be continued)

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert

> **Экономика:** Развиваем размышления и i3

В продолжение "размышлений" о монетизации - [ответил](https://github.com/u-transnet/info/issues/47#issuecomment-358504032) на варианты, предложенные @nat-brit 

> **Запуск блокчейна:** подготовка
> Поменять что-нибудь в скине стандартного кошелька, чтобы отличался от Bitshares

@EvgeniyPolyakov сегодня приоткрыл завесу над светлым будущим реф.кошелька Bitshares на службе пользователей u-transnet - начал кастомизацию интерфейса (скриншот НЕ прилагаю). Поэтому как только возникнет потребность в GUI к блокчейну u-transnet - он будет уже у нас  в активе и готов к внесению изменений и исправлений. 

**Симулятор** - новый (на самом деле старый) поток работ, который теперь мы можем возобновить благодаря @codename-art - сегодня довольно много и плодотворно общались, сформулировали [задачу](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-358273061) и поставили на скилл - симулятор официально возобновлен.

До [описания токенизации](https://github.com/u-transnet/info/issues/56) руки так и не дошли сегодня, прийдется наверстывать завтра

(to be continued)

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert 

> Но есть и хорошая новость - на днях я общался с потенциальным кандидатом на задачи по шлюзам, который имеет опыт работы в данной области. Если наш контакт по каким-либо причинам не прервется - работы над шлюзами возобновятся в начале 20х чисел января.

UP: @netral23 присоединился к команде (блок перевода скилла будет позже)

Напомню себе и команде локации добытых знаний в области шлюзостроения: 

- [Шлюз](https://github.com/u-transnet/codebase/tree/gate)
- [ERC20](https://github.com/u-transnet/codebase/tree/erc20)
- [Бот-аукционер](https://github.com/u-transnet/codebase/tree/exchange_bot)
- [Проект](https://github.com/u-transnet/codebase/projects/4) реализации схемы распределения токенов направлений и АП
- [Репозиторий Gateway](https://github.com/u-transnet/Gateway), в котором мы начинали развивать некоторые идеи, но дело не пошло 

> **Экономика:** Совместно с @Dima-Iron и @nat-brit ставим задачу @Dima-Iron (и меня в качестве консультанта) на разработку документа, упомянутого в #50 (тут)

По документу о токенизации разгорелась жаркая дискуссия - необходим ли он для сайта-тизера и в каком максимально простом виде можно представить [диаграммы i1-i3](https://www.draw.io/#Hu-transnet%2Finfo%2Fmodels-mpa-economy-i1-i2%2Fdrawings%2Fconcept-mpa-economy-i1-i2.xml) с дополнениями (после i3 вправо), формируемыми в рамках работ над #56 

> **Симулятор**

@codename-art [продолжает](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-358908475) проектировать механику обмена токенами: 
- резервирования РА под маршрут, 
- события фиксации обмена активами, 
- участники событий

(подробнее в [задаче](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-358908475))

> **Запуск блокчейна:** подготовка
> Поменять что-нибудь в скине стандартного кошелька, чтобы отличался от Bitshares

@EvgeniyPolyakov продолжает работы над ребрендингом референтного клиента Bitshares, а так же совместно с @mparkhomenko адаптацией кодовой базы Bitshares под наш форк ([задача](https://github.com/u-transnet/transnet.space/issues/5) по фиксу зависимостей в js)

> Докер 

[задача](https://github.com/u-transnet/codebase/issues/28) все еще не закрыта, @mparkhomenko отвлекался на задачи интеграции ([CORS на сайт](https://github.com/u-transnet/transnet.tech/issues/2)) и помогал @EvgeniyPolyakov

**Comment by cptn-solo** [comment]
@alecvert @Arteg0r @nat-brit пожалуй, это все, что успел за неделю из первоначального плана за исключением того, что забыл указать в отчетах. Транзакция перевода UTDEV предложена на учетке **utd-architect**

BLOCK #23687854

CREATE PROPOSAL |  
-- | --
Expiration time | January 21, 2018, 5:03:30 AM
Proposed operations | Transfer 1,225.00000 UTDEV from utd-architect to cptn-solo

**Comment by Arteg0r** [comment]
@kkrupovich заапрувил

**Comment by cptn-solo** [comment]
@Arteg0r 

> заапрувил

по-моему, не успел ;) - смотри, @nat-brit заапрувила:

BLOCK #23700682

UPDATE PROPOSAL |  
-- | --
Fee paying account | bkmfk
Proposal object id | 1.10.7795
Active approvals to add | bkmfk

**Comment by Arteg0r** [comment]
@kkrupovich 
#23694531
![image](https://user-images.githubusercontent.com/34586822/35192614-23795aec-fea7-11e7-9614-7abbb764a58d.png)

)) значит в разных вселенных заапрувили
