### ISSUE TITLE
Создание описания токенизации для сайта transnet.tech

### ISSUE THREAD

**Issue by Dima-Iron** [u-transnet/info#56]
В рамках #50 продолжается разработка документов, являющихся описанием всех блоков и текстов сайта transnet.tech. Документы необходимы для использования в качестве отправной точки для модификации текущего макета полноразмерной версии сайта transnet.tech коллегами (@jackal1527 и @EvgeniyPolyakov)

Коллеги @kkrupovich @nat-brit @alecvert, по данной задаче нужен созвон - обсудить ТЗ, объём, логику и структуру текста. Предлагаю завтра, 16 января.   

Ориентировочно в четверг, 18 января, обсудим черновик, потом внесем корректировки, чтобы на этой неделе задача была закрыта.

**Comment by cptn-solo** [comment]
@Dima-Iron 
По токенизации мы уже предпринимали несколько попыток сформулировать понятный документ, но тогда это делалось не для сайта - возможно, теперь пригодится: #26

**Comment by Dima-Iron** [comment]
BLOCK #23562089
TRANSFER  
From | dima-iron
To | utd-content
Quantity | 175.00000 UTDEV.SKILL

Сроки по задаче 15.01. - 19.01.2018

@kkrupovich @alecvert

**Comment by Dima-Iron** [comment]
Раздел "токенизация" для сайта transnet.
Драфт будет создан до 18.00 по мск 16.01.2018
[Заготовка документа](https://docs.google.com/document/d/1Bm8wfnKCT4xDGIV9l8UB1Hx40C6XYH3oK6XLycS1OJQ/edit)

**Comment by nat-brit** [comment]
К ТЗ:
1.[ Эволюция](https://golos.io/golos/@natasha/svyazannye-odnoi-cepyu-minimum-chto-nuzhno-znat-pro-blokchein) токенов
2. Описание токенов ([типы](https://en.wikipedia.org/wiki/BitShares)) - базовый, UIA, MPA
3. Описание токенов [внутри Transnet](https://github.com/u-transnet/info/wiki/%D0%93%D0%BB%D0%BE%D1%81%D1%81%D0%B0%D1%80%D0%B8%D0%B9)
4. Описание ролей участников Transnet (Вендор, Оператор АП, Заверители, подрядчики, пользователи, инвестор, и пр)
5. Визуально нужно 2 картинки: диаграмма по токенам (внутренний учет и внешние обмены) и вот эту использовать: 
![1828](https://user-images.githubusercontent.com/30142436/34985338-6817be30-fabc-11e7-83f6-ec7c0f2016b1.png) - задача @kkrupovich 

@kkrupovich @alecvert

**Comment by cptn-solo** [comment]
@Dima-Iron 

> 2. Описание токенов (типы) - базовый, UIA, MPA
> 3. Описание токенов внутри Transnet
> 4. Описание ролей участников Transnet (Вендор, Оператор АП, Заверители, подрядчики, пользователи, инвестор, и пр)

в info/wiki в [глоссарий](https://github.com/u-transnet/info/wiki/%D0%93%D0%BB%D0%BE%D1%81%D1%81%D0%B0%D1%80%D0%B8%D0%B9) добавил подрядчиков и транзитные активы, надо продолжать, текущая задача даст выхлоп для глоссария неплохой ;)

@nat-brit 
> 5. Визуально нужно 2 картинки: диаграмма по токенам (внутренний учет и внешние обмены) и вот эту использовать:

@alecvert [задача](https://github.com/u-transnet/info/issues/9) (#9 ) про иерархию активов - схема токенизации АП - не нашел исходники к сож., надо спрашивать @iSergeevich

**Comment by cptn-solo** [comment]
@Dima-Iron @nat-brit 
Откомментил немного док, сегодня буду рисовать схемку пытаться.

**Comment by Dima-Iron** [comment]
Будут ли еще правки к [документу](https://docs.google.com/document/d/1Bm8wfnKCT4xDGIV9l8UB1Hx40C6XYH3oK6XLycS1OJQ/edit) в текущем виде?
Предлагаю добавить схемы от Кости и закрыть итерацию, перейдя к описанию концепции и построению роадмэп.
К доработке раздела по токенизации предлагаю вернуться в дополнительной итерации после завершения формирования концепции.

 @kkrupovich @nat-brit @alecvert

**Comment by cptn-solo** [comment]
@Dima-Iron @nat-brit @alecvert 

> Предлагаю добавить схемы от Кости и закрыть итерацию, перейдя к описанию концепции и построению роадмэп.

Согласен. Нужно выбрать/сформулировать и заскилловать следующую задачу. 

> К доработке раздела по токенизации предлагаю вернуться в дополнительной итерации после завершения формирования концепции.

Согласен. Предлагаю закрывать итерацию, ссылку на текущую задачу желательно зафиксировать в wiki тизера ([Контент и разделы](https://github.com/u-transnet/www-teaser/wiki/%D0%9A%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82-%D0%B8-%D1%80%D0%B0%D0%B7%D0%B4%D0%B5%D0%BB%D1%8B)?)

@nat-brit вообще все задачи на разработку документов, как и задачи на разработку софта,  должны включаться в milestone с датой. Milestone имеют ряд любопытных применений, например [такое](https://github.com/bitshares/bitshares-core/milestone/7?closed=1)

**Comment by nat-brit** [comment]
@kkrupovich 
> ссылку на текущую задачу желательно зафиксировать в wiki тизера (Контент и разделы?) - 
все задачи на разработку документов, как и задачи на разработку софта, должны включаться в milestone с датой. 

Поэтому первоочередная задача - определиться с milestones, потом с ответственными за направления:) Ну и обучить, что и где и как фиксировать:))) Сейчас, работая с сайтом я уже вижу, какие есть проблемы, но пока у меня не сложилось понимание, как сделать все удобно и наглядно. По разработкам - это одно, но по контенту, обсуждению экономики и токенизации, и по дизайну все-таки очень неудобно. Про игру и симулятор тоже путаюсь в ветках. Ладно, разберемся:)

**Comment by cptn-solo** [comment]
@Dima-Iron @nat-brit 

> К доработке раздела по токенизации предлагаю вернуться в дополнительной итерации после завершения формирования концепции.

BLOCK #23736091

TRANSFER |  
-- | --
From | utd-content
To | dima-iron
Quantity | 175.00000 UTDEV

Спасибо!

PS: по поводу внедрения схемы - вопрос, т.к. мы не решили должен ли быть этот раздел (токенизация) в документе.
