### ISSUE TITLE
Иллюстрация: Схематично - Физическая структура TRANSNET

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#6]
Вставить в створ абзаца поясняющую диаграму: 
общее пространство, внутри линии с кружками станций и "движущиеся" кружки подвижного состава. Можно добавить стиль из digitize with unity и изобразить передачу информации по путевой структуре (подводка к след. абзацу)
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBQ)

**Comment by cptn-solo** [comment]
Это схематичная (адаптированная, вид "сверху", абстрактно) переработка  А0 на листе CONCEPT в [книге схем и диаграмм](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Funity_concept.xml)

<img width="701" alt="screen shot 2017-09-25 at 23 26 36" src="https://user-images.githubusercontent.com/1105555/30829350-3903634a-a249-11e7-98a3-d46ebdc1f433.png">

**Comment by iSergeevich** [comment]
![scheme2](https://user-images.githubusercontent.com/31988874/30937594-b7aa426a-a3f0-11e7-89d8-2ce781e3705f.png)


> Вообще вариант надо оставить для истории, т.к. возможно он нам пригодится где-то в презентациях подробных. И я удалил общую схему (доступна [тут](https://user-images.githubusercontent.com/31988874/30937593-b7a508c2-a3f0-11e7-89db-faac99fee087.png))

**Comment by iSergeevich** [comment]
![scheme4](https://user-images.githubusercontent.com/31988874/30939212-201b04d8-a3f6-11e7-9421-65d5a22109a4.png)
увеличенная

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich не та стилистика картинки на мой взгляд абсолютно и цветовая гамма, комиксы как будто. У нас же высокотехнологичный проект

**Comment by cptn-solo** [comment]
> @kkrupovich @iSergeevich не та стилистика картинки на мой взгляд абсолютно и цветовая гамма, комиксы как будто. У нас же высокотехнологичный проект

В общем, я согласен с @alecvert - это не схематично ни разу.

**Comment by alecvert** [comment]
@iSergeevich @kkrupovich и что? где продолжение?

**Comment by iSergeevich** [comment]
![scheme5](https://user-images.githubusercontent.com/31988874/31648584-fe45591c-b327-11e7-940e-6261643637de.png)

**Comment by cptn-solo** [comment]
Коммент отвязался от исходного текста концепции, не могу найти в документе место, к которому эту иллюстрацию заказывал, но она вообще-то очень важная. 
@iSergeevich , думаю, можно сделать компактнее - не показывать всю карту, а ограничиться какой-нибудь узнаваемой частью, буквально, четверть Африки на фоне показать, больше не надо. 
По зум-врезке - цифры из шариков верхней линии можно убрать. В исходнике они нужны были для комментариев как референс, к иллюстрации это не относится. Но вообще конечно это все не то. Это просто калька с моей иллюстрации, я надеялся на креатив хотя бы какой-то минимальный.

**Comment by cptn-solo** [comment]
@iSergeevich @alecvert коллеги, эту совсем немного надо дожать
