### ISSUE TITLE
Неделя #4/2018 

### ISSUE THREAD

**Issue by nat-brit** [u-transnet/info#60]
## Повестка дня стейкхолдеров U-TRANSNET *

- Вакансии - актуализация [доски](https://github.com/u-transnet/info/projects/4) (перманентная задача) @nat-brit @kkrupovich @Arteg0r 
- Концепция образовательного направления и актива ([задача](https://github.com/u-transnet/info/issues/63)) @nat-brit @ipral50 
- Тексты описаний токенов SKILL, DEV, CORE, GAME, KIT (в рамках [задачи](https://github.com/u-transnet/info/issues/56)) -  @kkrupovich @nat-brit @Dima-Iron @alecvert 

**TRANSNET SPACE**
- Сайт - сформировать ТЗ на основе [Плана развития медиаресурсов](https://docs.google.com/document/d/1DLpWe-TV9X8ma2ibIuSyCvkH3kYB5Dyp7cOefm6UfBE/edit?ts=5a648999) ([задача](https://github.com/u-transnet/info/issues/62)) команды U-TECH и платформы TRANSNET SPACE. @kkrupovich @alecvert @rossul @Dima-Iron 
- Сформировать ТЗ для страниц "[дорожная карта](https://docs.google.com/document/d/1RYW539VZRiQn3jnMuGkKvbW2UB2up15sH3m_ZvLBKTM/edit)", "[концепция](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Fdrawings%2Fconcept-full.xml)", и продолжаем работать по главной (наполнение и макет). @Dima-Iron @jackal1527 
- Репозиторий wiki (?) - сформировать требования к задаче @nat-brit @kkrupovich
- Закончить страницу [по токенизации](https://docs.google.com/document/d/1Bm8wfnKCT4xDGIV9l8UB1Hx40C6XYH3oK6XLycS1OJQ/edit) ([задача](https://github.com/u-transnet/info/issues/56#issuecomment-359269468)), ждем диаграмму @kkrupovich 
- Пока ждем новую медиа-концепцию:
- - На основании результатов [задачи](https://github.com/u-transnet/info/issues/56) [спроектировать макет веб-страницы по токенизации](https://github.com/u-transnet/www-teaser/issues/93) с иллюстрациями для видов токенов платформы (skill-dev-[core|game|kit]-UTT) (@jackal1527 @RomaRAD )
- -  [Пробуем переверстать макет](https://github.com/u-transnet/www-teaser/issues/94) с новой графикой для шапки и блоком "больше чем блокчейн"

`* Стейкхолдерами можно считать держателей любых токенов, эмитированных U-TECH на правах инициатора первых направлений деятельности Transnet Space, поскольку существует строгая иерархия токенов, голосующих в обоих направлениях: 
SKILL <-> DEV <-> [CORE|GAME|KIT|...] <-> UTT`

### UTCORE (#61)

**Экономика блокчейна**
- Проработка сценариев монетизации инфраструктурных токенов платформы в целевом блокчейне. 
- Проработка [каналов эмиссии UTTа](https://github.com/u-transnet/info/issues/47), базового актива блокчейна .
@u-transnet (модераторы @kkrupovich @alecvert @nat-brit )

**Координация запуска (продолжение #52)**
- запустить узлы заверителей блокчейна, сформировать первый круг доверия нового DAC на Graphene - первоочередная по важности
- работа над кастомизацией интерфейса (форк референтного кошелька Bitshares) с целью ребрендинга под символику U-Tech
@kkrupovich 

### UTKIT  (#61)
- Поиск системного [аналитика, архитектора](https://github.com/u-transnet/info/issues/55) (запуск направления UTKIT)
- Возобновлены работы над [симулятором](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-358273061)
- Токенизация TRANSNET в блокчейне: система управления и мониторинга, схема трансакций в блокчейн. Задачи в работе [тут](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-358908475) 
@codename-art 

### UTGAME
- разработка [прототипа](https://docs.google.com/document/d/1OpifdQG-QijTVM6hBsykD7NuHINYavPw3FnZAgfqfNE/edit?ts=5a5e6c2e#heading=h.4v3fabyy0mik) +интерфейс оперативного режима Игры, продолжение [итерации](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-358908475)
- Закрыть вакансию по[ геймдизайнеру](https://github.com/u-transnet/info/issues/53)
 @Arteg0r 

Дополнения и пожелания приветствуются.

**Comment by cptn-solo** [comment]
@nat-brit 
Отличный план. Спасибо! Я раскидал задачи по группам более явно, и параллельно подумал над структурой наших отчетов. 
@nat-brit @Arteg0r @alecvert предлагаю использовать эту задачу в качестве основного инструмента для [наведения порядка](https://github.com/u-transnet/info/issues/58#issuecomment-359304791) в наших репозиториях
@nat-brit составление такого обзорного плана и ведение отчета по нему - достаточно интересная задача, как считаешь ? ;) тот, кто возьмет на себя эту работу - будет вхож во все двери проекта ;)

**Comment by nat-brit** [comment]
> составление такого обзорного плана и ведение отчета по нему - достаточно интересная задача, как считаешь ?

Да. Пока не наведем порядок, хоть так:) Пока беру это на себя, но обзоры по ссылкам должен составлять пиар-менеджер, который будет вести блог Транснет. Сейчас есть 3 человека уже, которым можно поручить составление обзоров. Могу сформировать задачу.
@kkrupovich @alecvert @Arteg0r

**Comment by cptn-solo** [comment]
@nat-brit 
> обзоры по ссылкам должен составлять пиар-менеджер

обзоры - это интервью с исполнителями? по факту это задача менеджера проекта - выявление рисков и работа с ними (@Arteg0r @rossul поправьте меня, если я несу чушь) - но если у нас нет менеджера проекта в классическом понимании, то можно попытаться заменить эту часть процесса чем-то вроде публичной порки просрочивших задачи исполнителей ;))) Тогда интервью будет как раз сбором обратной связи от исполнителей и информирование стейкхолдеров о статусе работ в рамках направлений - если стейкхолдеры решат поставить к каким-то потокам работ менеджеров - это их право и выбор (финансирование).

**Comment by Arteg0r** [comment]
@nat-brit @kkrupovich 
Безусловно, обзор обеспечивает отличную наглядность движения работ по всем направлениям.

**Comment by nat-brit** [comment]
@kkrupovich 
В конце недели под этой задачей #60 будет коммент с результами. И линки на выполненные задачи. (от меня)
Порка вряд ли понадобится, пока мы оперируем с квалификациоными токенами:)
Про интервью не очень поняла. На мой взгляд достаточно, что "пиар-менеджер" или просто человек из команды по контенту внятными словами опишет то, что найдет по ссылкам исполненных задач: сделано то-то и так-то, тут речь идет о том-то... и будет выкладывать эти обзоры в блог (либо на Медиум, либо на Стимит) и на наш сайт (кнопка "блог").
И очень важно отладить механизм по постановке ТЗ - кто кому ставит, кто принимает работу и закрывает задачу.

**Comment by cptn-solo** [comment]
@nat-brit 
> И очень важно отладить механизм по постановке ТЗ - кто кому ставит, кто принимает работу и закрывает задачу.

это классический челлендж любого процесса разработки - обычно разработкой ТЗ занимается аналитик, но в нашем процессе этот этап и его роли мы пытаемся заменить совместным формулированием постановки задачи (лейбл <img width="85" alt="help wanetd" src="https://user-images.githubusercontent.com/1105555/35218107-7021c46a-ff7e-11e7-9854-3d37f2589216.png">)

> внятными словами опишет то, что найдет по ссылкам исполненных задач

Для этого призываю проводить разъяснительную работу с кандидатами и исполнителями задач наших репозиториев. Есть документ wiki, в котором я описывал [регламент постановки и ведения задач](https://github.com/u-transnet/info/wiki/2.3.-%D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D0%B8-%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F-%D0%B7%D0%B0%D0%B4%D0%B0%D1%87-(issue))

**Comment by nat-brit** [comment]
BLOCK #23809937
From | bkmfk
To | utd-pm
Quantity | 875.00000 UTDEV.SKILL
Период с 22 по 27 января включительно
@kkrupovich @Arteg0r  @alecvert

**Comment by nat-brit** [comment]
**Результаты недели:**

В рамках задачи #58 созданы новые репозитории - информационные (ABOUT, CONTRIBUTE, UT-SCHOOL, UT-CORE, UT-GAME, UT-KIT), предназначенные для новых направлений деятельности и компонентов будущей платформы (UT-DESIGN, UT-WORKS).

В репозитории[ CONTRIBUTE](https://github.com/u-transnet/CONTRIBUTE) (задачи, ищущие исполнителя)  будут размещаться сформулированные верхнеуровневые задачи/вакансии с бюджетом). Начата работа над [ботом в Telegram](https://github.com/u-transnet/codebase/issues/49).
 
Репозиторий [UT-SCHOOL](https://github.com/u-transnet/UT-SCHOOL) предназначен для работы над концепцией образовательного направления. Готова [первая диаграмма](https://github.com/u-transnet/info/issues/63) по взаимодействию сторон образовательного процесса.   
 
На примере [UT-WORKS](https://github.com/u-transnet/UT-WORKS) мы сможем мигрировать управление требованиями (задачи, проекты) в Jira , оставив управление конфигурацией продукта (код, документация, дорожная карта) в Github. 

Запущено новое направление [UT-DESIGN](https://github.com/u-transnet/UT-DESIGN), руководитель @rossul. 
Кардинальные изменения [в отношении всех работ по сайту](https://github.com/u-transnet/UT-WORKS/issues/1), да и по всему направлению:)

Утверждены названия: 
**U-TRANS** - название платформы.
 **U-TECH** - название команды, инициативной группы по разработке платформы. 

В рамках задачи #59 продолжаем [оптимизировать внутренние процессы](https://github.com/u-transnet/info/issues/59#issuecomment-361448692) - управление требованиями выносим в Jira. 

**UTCORE**
По запуску блокчейна:
@netral23 провел [предварительный анализ](https://github.com/u-transnet/Gateway/issues/7) реализации Atomic Swap в Scorum/decret. 
@mparkhomenko и @EvgeniyPolyakov проделали большую работу по обновлению кодовой базы U-Trans. Готова первая версия [readme для докера](https://github.com/u-transnet/codebase/issues/51) - отчеты по docker и composer.

**UTKIT**
 @codename-art начал работу в качестве руководителя направления UTKIT 
Работа над симулятором идет полным ходом: [альбом диаграмм](https://www.draw.io/#Hu-transnet%2Ftransnet-simulator%2Fconcept%2Fconcept%2Fdrawings%2Fut-simulator.xml) и [идеи](https://github.com/u-transnet/info/issues/61) тут . Есть понимание архитектуры симулятора и внутренней механики в ее транспортной, прикладной, инженерной части. Создана [Доска задач](https://github.com/u-transnet/transnet-simulator/projects/2).

**UTGAME**
Отобраны [два кандидата](https://github.com/u-transnet/info/issues/53#event-1448445348) на вакансию геймдизайнера. [Вакансия](https://github.com/u-transnet/info/issues/53) закрыта. Поставлены новые [задачи ](https://github.com/u-transnet/Gamedev/issues/6) по координации работ по игровому направлению.

@kkrupovich  @Arteg0r  @alecvert

**Comment by cptn-solo** [comment]
@nat-brit @alecvert @Arteg0r предложил транзакцию на **utd-pm**
BLOCK #24002260

CREATE PROPOSAL |  
-- | --
Expiration time | February 1, 2018, 3:53:15 AM
Proposed operations | Transfer 875.00000 UTDEV from utd-pm to bkmfk

**Comment by cptn-solo** [comment]
@nat-brit несмотря на ряд нюансов - выглядит бодро. Что заметил:

> В репозитории CONTRIBUTE (задачи, ищущие исполнителя) будут размещаться сформулированные верхнеуровневые задачи/вакансии с бюджетом). Начата работа над ботом в Telegram.

- на самом деле это не только телеграм-бот, но и веб, и встраивание в референтный кошелек Bitshares/U-Transnet. 
- под управление разработкой этого приложения (биржа задач и ресурсов) создан отдельный репозиторий [UT-WORKS](/u-transnet/UT-WORKS)

> Репозиторий UT-SCHOOL предназначен для работы над концепцией образовательного направления. Готова первая диаграмма по взаимодействию сторон образовательного процесса.

новости этого направления - токенизацию, предложенную в "[первой диаграмме](https://github.com/u-transnet/info/issues/63)" обкатали на первых потенциальных "гарантах" (доверенных учебных заведений и провайдеров образовательных услуг). Схему было бы неплохо обвязать каким-то базовыми интерфейсами, например 
- регистрации абитуриентов (в Bitshares/u-Trans)
- передачи токенов сторонам по стадиям процесса  
`TBD`

> @codename-art начал работу в качестве руководителя направления UTKIT

Не думаю, что @codename-art обрадуется такому повышению ;) но де-факто так оно и есть - в отсутствие штата единственный участник сам себе хозяин :)) Интересно в этом направлении другое - его репозиторий. Масштабируемость. При желании это направление можно нагрузить потоком задач практически любой сложности - при условии четкого разделения функциональности на блоки и выделения блоков в отдельные проекты. 

> UTGAME Отобраны два кандидата на вакансию геймдизайнера. Вакансия закрыта. 

А вы знаете, что география нашего проекта уже включает 4 страны и 8 городов? Если же не обращать внимания на скилл - и того больше.

**Comment by nat-brit** [comment]
С дополнениями выглядит еще бодрее:) Спасибо!
