### ISSUE TITLE
[Координация #4/2018] Запуск блокчейна + концепция + разработка

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#61]
Предыдущий отчет #52 
Общий план на текущую неделю #60 

## Деятельность в рамках U-TECH/TRANSNET SPACE

- участие в [формулировании идеи нового направления (образовательный токен)](https://github.com/u-transnet/info/issues/63) @nat-brit @ipral50 @alecvert 
- участие в [формулировании плана развития медиаресурсов](https://github.com/u-transnet/info/issues/62)
- участие в [наведении порядка в хабе](https://github.com/u-transnet/info/issues/58#issuecomment-359304791)

## Локальный план по направлению UTCORE

**Экономика**
- Закончить диаграмму для иллюстрирования методологии токенизации, начатую в рамках [задачи](https://github.com/u-transnet/info/issues/56#issuecomment-359269468) - на текущий момент рассматриваю вариант развития "иерархии" основных токенов, упомянутую в качестве пасхалки в #60 (`* Стейкхолдерами можно считать держателей любых токенов, эмитированных U-TECH на правах инициатора первых направлений деятельности Transnet Space, поскольку существует строгая иерархия токенов, голосующих в обоих направлениях: SKILL <-> DEV <-> [CORE|GAME|KIT|...] <-> UTT`)

**БЧ**
- [Определиться](https://github.com/u-transnet/codebase/issues/15) с параметрами генезиса целевого блокчейна - какие есть, на какие надо обратить внимание (@mparkhomenko )
- Запустить несколько нод заверителей с использованием [докера](https://github.com/u-transnet/codebase/issues/28)
- В идеале у нас должен появиться какой-то репозиторий докеров с описаниями и инструкциями, и, возможно, задача про [docker copmpose](https://github.com/u-transnet/codebase/issues/38) как раз об этом
- Протестировать инструкции и сам докер-контейнер, предоставить фидбэк @mparkhomenko и @EvgeniyPolyakov для формулировки следующих задач в рамках подготовки софта для развертывания на узлах сети, например:
- - [кастомизация UI](https://github.com/u-transnet/utransnet-ui/projects/1) ([задача](https://github.com/u-transnet/utransnet-ui/issues/1) по текстам в реф-кошельке) - ребрендинг надо постепенно вытеснять более существенными задачами - например: 
- - попробовать [интегрировать последние фиксы из upstream](https://github.com/u-transnet/utransnet-ui/issues/2)
- - начать [работы](https://github.com/u-transnet/witness-scripts/projects/1) по адаптации скриптов валютных котировок и других скриптов, выполняющихся на узлах сети и создающих транзакции в бч от лица заверителей

**Шлюзы и распределение токенов направлений** 
- Сформулировать задачи и возобновить работы по направлению [шлюзов](https://github.com/u-transnet/codebase/tree/gate) и движков распределения ([ERC20](https://github.com/u-transnet/codebase/tree/erc20), [Бот-аукционер](https://github.com/u-transnet/codebase/tree/exchange_bot)) токенов направлений ([проект](https://github.com/u-transnet/codebase/projects/4), [экономика](https://github.com/u-transnet/info/issues/47)) ( @netral23 @EvgeniyPolyakov @mparkhomenko )

## Локальный план по направлению UTKIT

- продолжаем актуализировать и дополнять [архитектуру](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-359343007) и сценарии использования симулятора
- общая [концепция UIKIT](https://github.com/u-transnet/transnet-simulator/issues/5) - интегрируем симулятор в направление 
- закладываем базис под проектирование смежных с симулятором и движком токенизации инфраструктурных АП подсистем ([мониторинг и управление](https://github.com/u-transnet/transnet-simulator/issues/6), [бронирование](https://github.com/u-transnet/transnet-simulator/issues/7))

**Comment by cptn-solo** [comment]
@Arteg0r @nat-brit @alecvert предложил @codename-art попробовать себя в качестве руководителя направления UTKIT - можно начать с формулировки недельных планов, подобных настоящей задаче и ведению отчетности по нему в формате наших управленческих задач. Не думаю, что это будет большой проблемой для него, если мы будем доступны для обсуждения ключевых вопросов, возникающих в ходе работ. В качестве архитектора платформы готов оказывать всяческую поддержку со своей стороны.

**Comment by cptn-solo** [comment]
@alecvert @nat-brit @Arteg0r 

BLOCK #23757296

TRANSFER |  
-- | --
From | cptn-solo
To | utd-architect
Quantity | 875.00000 UTDEV.SKILL

Скилл под работы с 22 по 26 января 2018 включительно

**Comment by cptn-solo** [comment]
@alecvert @nat-brit @Arteg0r 

> Локальный план по направлению UTKIT
> продолжаем актуализировать и дополнять архитектуру и сценарии использования симулятора

Посмотрите, какие диаграммы рисует @codename-art 👍 

<img width="824" alt="screen shot 2018-01-23 at 01 42 15" src="https://user-images.githubusercontent.com/1105555/35248322-c29f1da4-ffde-11e7-858b-3c4bcff88641.png">

[Симулятор](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-359343007) развивается просто семимильными шагами, его [альбом диаграмм](https://www.draw.io/#Hu-transnet%2Ftransnet-simulator%2Fconcept%2Fconcept%2Fdrawings%2Fut-simulator.xml) скоро догонит по объему общий альбом концепта Transnet Space ;)

Объективно - этот симулятор является весьма интересным проектом сам по себе, и, возможно, заставит нас изменить приоритеты в отношении тактического режима Игры - имея такие наработки по токенизации операционной деятельности физической инфраструктуры проектов, мы просто обязаны рано или поздно запустить визуализацию работы транспортной сети на блокчейне ;) @Arteg0r 

Из супер-последних мега-идей по симулятору - использовать кастомный тип транзакций для отправки сообщений подсистемы управления и мониторинга (ПУМ) через пиринговую сеть самого блокчейна, что сделало бы ПУМ физической сети TRANSNET полностью децентрализованной и автономной. Однако есть один нюанс - надо убедиться, что такой подход применим на практике - частота сканирования систем мониторинга обычно довольно высока, и это может повлечь за собой избыточную нагрузку на блокчейн. Но я уверен, что мы так или иначе сможем воспользоваться этой отличной идеей.

PS: по сути мы уже думали о пиринговой архитектуре для ПУМ, но думали об интеграции в ПУМ-сеть клиентского ПО, развернутого на каждом ОФИ. Новизна вчерашней идеи заключается именно в том, что мы не разворачиваем для ПУМ отдельную инфраструктуру, а используем P2P модуль ПО Graphene. @codename-art поправит меня, если я ошибаюсь.

> Локальный план по направлению UTCORE
> **БЧ:** кастомизация UI (задача по текстам в реф-кошельке) - ребрендинг надо постепенно вытеснять более существенными задачами

Благодаря @EvgeniyPolyakov и @mparkhomenko с реф-кошельком мы предварительно разобрались и готовы аккуратно стилизовать его под наш проект (логотипы, названия блоков и тексты сообщений - где это применимо и не относится к коду именно Bitshares - заменяем на наши названия и тексты). Цель кастомизации - не выдавать реф-колешек Bitshares за свою разработку, а использовать наработки проекта Bitshares в своем проекте и продолжать развивать экосистему - если какие-то ошибки исправляются в Bitshares - мы вносим исправления у себя, и наоборот - если мы находим ошибку или разрабатываем функционал, который может ипользоваться и в Bitshares - заливаем наработки в upstream - это общепринятая практика в opensource проектах, и отчасти ради такого "культурного обмена" мы и выбрали этот подход для нашего проекта разработки. В перспективе, безусловно, реф-кошелек останется инструментом гиков и самой команды, а широкий круг пользователей разбредется по своим, оптимизированным под их роли, интерфейсам. Пока же мы ищем и заменяем брендованные блоки, используя [задачу](https://github.com/u-transnet/utransnet-ui/issues/1)

(to be countinued)

**Comment by cptn-solo** [comment]
@nat-brit @alecvert @Arteg0r резюмирую сегодняшние (вчерашние) достижения.

> Деятельность в рамках U-TECH/TRANSNET SPACE

Как мы все уже знаем, работы над сайтом приостановлены, поскольку его концепция снова претерпевает изменения. Но на этот раз мы собираемся подойти к вопросу более основательно, поскольку получили очень ценный фидбэк от @rossul относительно текущего макета и наполнения тизера. Более того, мы решили не откладывать реорганизацию репозиториев Github, иначе не удастся реализовать задуманный редизайн сайта -  [наведение порядка в хабе](https://github.com/u-transnet/info/issues/58#issuecomment-359304791) началось.
Сама причина, по которой мы меняем дизайн, неплохо описана в комментариях к [плану развития медиаресурсов](https://github.com/u-transnet/info/issues/62) - мы поняли, на какой именно целевой аудитории хотим сфокусироваться - на для желающих присоединиться к нашему сообществу участников, на тех, с кем мы общаемся каждый день - энтузиасты, разработчики, аналитики - коллеги.   И вот для этой целевой аудитории нам нужно сделать хаб u-transnet более понятным и интуитивным. 

Но все-таки отдельное спасибо хотелось бы сказать @RomaRAD @jackal1527 и @EvgeniyPolyakov за [красоту](https://github.com/u-transnet/www-teaser/issues/94), которая у нас получилась в последней итерации сайта.

> Локальный план по направлению UTKIT

Удалось очень подробно обсудить с @codename-art текущее понимание [архитектуры](https://github.com/u-transnet/transnet-simulator/issues/6#issuecomment-360277810) симулятора и вообще внутренней механики Transnet Space именно в ее транспортной, прикладной, инженерной части. 
Что для меня стало особенно серьезным откровением:
- по нашим предварительным схемам, подсистема управления и мониторинга транспортной сети, подобной Transnet, действительно может быть децентализованной и функционирующей исключительно на инфраструктуре блокчейна и данных, доступных в нем. На высокопроизводительных блокчейн-движках, подобных Graphene (движок u-transnet) и, вероятно, в будущем, EOS, эта схема, вероятно, станет мэйнстримом, т.к. в нее прекрасно ложатся любые задачи по автоматической доставке грузов в сетях с возможностью линейного контроля. 

- на [схемах](https://github.com/u-transnet/info/issues/61#issuecomment-359746027) @codename-art я впервые увидел UTT "в работе", до сих пор мои диаграммы не опускались на прикладной уровень. Это развеяло миф о том, что токенизация внутреннего обмена между ОФИ отвязана от UTT. Нет. UTT в этих схемах служит активом, который непосредственно запускает процесс оказания услуги :
<img width="944" alt="screen shot 2018-01-25 at 01 04 09" src="https://user-images.githubusercontent.com/1105555/35359596-bc4448e2-016b-11e8-9b52-5bf16b4fc8dd.png">

`Особенно внимательные могут на этом фрагменте заметить новое направление, которое скоро появится в спейсе, объявляется конкурс на его название`

> Локальный план по направлению UTCORE

@netral23 провел [предварительный анализ](https://github.com/u-transnet/Gateway/issues/7) реализации atomic swap в Scorum/decred, который показал нам в деталях - что происходит в сети биткойна в процессе осуществления атомарного обмена. Теперь мы будем исследовать сторону Graphene. Какие-то соображения по реализации начинают появляться, но вопросы остаются. Что порадовало - под утро в архитектуру шлюза опять постучались делегаты/заверители ;)))

(to be continued)

**Comment by cptn-solo** [comment]
@Arteg0r @alecvert @nat-brit 
Немного магии от @mparkhomenko  - отчеты по [docker](https://github.com/u-transnet/codebase/issues/28#issuecomment-360506151) и [composer](https://github.com/u-transnet/codebase/issues/38#issuecomment-359978583) - задачам, связанным с запуском блокчейна. 
Но это еще не пакет для установки. Нам нужна инструкция, readme для докера. [Задача](https://github.com/u-transnet/codebase/issues/51) сформулирована, сделаем. 

После созвона с @alecvert решил дать ход [задаче](https://github.com/u-transnet/codebase/issues/49) по автоматизации работы со скиллом (про биржу "подрядчиков" и "проектов"). Вообще предлагаю всегда держать про запас пару-тройку внутренних проектов с невысоким приоритетом, чтобы не терять время зря, когда поток приоритетных задач останавливается, или иссякает.

(to be continued)

**Comment by cptn-solo** [comment]
@nat-brit @alecvert @Arteg0r 

> Локальный план по направлению UTCORE
> Шлюзы и распределение токенов направлений

Благодаря героическим усилиям @netral23 , теперь мы [знаем](https://github.com/u-transnet/Gateway/issues/7#issuecomment-360774627), как устроен атомарный своп между биткойном и графеном в реализации Scorum/Decred, и, безусловно, постараемся использовать эти знания в нашем проекте. Судя по всему, scorum пошел по каноническому пути расширения функциональности, предусмотренной во фреймворке Graphene - на уровне ядра создали кастомный объект и обработчик к нему. Этот подход хорош своей академичностью, но требует изменения кода ядра, что является само по себе довольно ответственной задачей. С другой стороны, начинать разбирать функционал ядра в любом случае прийдется хотя бы потому, что, кроме атомарных свопов, нам совершенно не помешали бы, например, распределения актива по заранее настроенным параметрам (пропорциональное распределение поступающих платежей по заранее указанным учетным записям `TODO: создать задачу`).  В общем, посмотрим, как дальше пойдут дела.
Кроме того, возможно, вариант, предложенный Scorum, будет затруднителен к реализации в той версии ядра, на котором построены Bitshares  и U-Transnet (Scorum ближе к Steemit), косвенные подтверждения чему я недавно видел в тематическом чате между разработчиками Bitshares и Scorum. В таком случае мы вернемся к варианту, который прорабатывали ранее - используем механизм подтверждения, построенный на доверии активным заверителям блокчейна.

> Локальный план по направлению UTGAME

Картинка от @codename-art для привлечения внимания :) 

![ut-simulator 1](https://user-images.githubusercontent.com/1105555/35463254-c7bf76c4-0300-11e8-992e-62e2915c9749.png)

На самом деле было несколько важных моментов. 
- [Возможно](https://github.com/u-transnet/transnet-simulator/issues/2#issuecomment-360801762), симулятор все же будет на Java, и мы вплотную приближаемся к Graphenj (Привет, @kenCode ;)
- Minecraft написан на Java. Совпадение? Не думаю (с)
- Мы [отказались](https://github.com/u-transnet/transnet-simulator/issues/1#issuecomment-360796745) от proposed transaction для резервирования маршрута. Это действительно было легко.
- Вероятно, на следующей неделе начнется разработка (до сих пор было проектирование)
- Так же на следующей неделе мы с @codename-art попробуем сформулировать задачу и вакансию для технологического прототипа более корректно

PS: @codename-art - надо не забыть про вариант с whitelisting для ОФИ в целях защиты от атак загрузкой ресурсного актива. Куда бы это воткнуть? В диаграмму может какую-то? Проверим  применимость на этапе разработки.

(to be continued)

**Comment by nat-brit** [comment]
Все внимательно читаю, но откомментировать вряд ли смогу:) Выглядит многообещающе:) Полностью поддерживаю предложение "попробовать @codename-art в качестве руководителя направления UT-KIT":)

**Comment by cptn-solo** [comment]
@nat-brit @alecvert @Arteg0r коллеги, предлагаю подтвердить транзакцию на учетке  **utd-architect**

BLOCK #23974055

CREATE PROPOSAL |  
-- | --
Expiration time | January 31, 2018, 4:16:52 AM
Proposed operations | Transfer 875.00000 UTDEV from utd-architect to cptn-solo

**Comment by Arteg0r** [comment]
@kkrupovich Подтвердил.
