### ISSUE TITLE
Работа над наполнением сайта и стратегией продвижения 

### ISSUE THREAD

**Issue by Dima-Iron** [u-transnet/info#64]
Коллегами @nat-brit и @kkrupovich  в рамках задач #60 и #62 была начата работа по формированию ТЗ для сайта и последующему его наполнению.    

Принимаю непосредственное участие в создании описаний разделов сайта-  страниц "роли участников", "дорожная карта", "концепция", а также продолжаю работать по наполнению главной страницы. 

@alecvert @nat-brit @kkrupovich

**Comment by cptn-solo** [comment]
@Dima-Iron 
Предлагаю так же рассмотреть [результаты](https://github.com/u-transnet/info/issues/62#issuecomment-360078763) работы над планом развития медиаресурсов - возможно, наполнение сайта ("базовые понятия") стОит сформулировать вне его - а именно - в корневых репозиториях направлений в Github.

В этом контексте особенно полезным будет развитие документов, находящихся в [корневом репозитории](https://github.com/u-transnet/info) направления UTCORE (платформа):
- [Конституции](https://github.com/u-transnet/info/wiki/0.-%D0%9A%D0%BE%D0%BD%D1%81%D1%82%D0%B8%D1%82%D1%83%D1%86%D0%B8%D1%8F) блокчейна , 
- [Миссии U-TECH](https://github.com/u-transnet/info/wiki) в качестве инициатора создания методологии и платформы ее реализующей), 
- [Приглашения](https://github.com/u-transnet/info/wiki/2.-%D0%9F%D1%80%D0%B8%D0%BD%D1%8F%D1%82%D1%8C-%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%B5) к участию в проекте.

Так же эта информация будет весьма полезна в процессе работы над ТЗ сайта (возможно, [этот документ](https://docs.google.com/document/d/13tpKqF05BsCL2mAKcFEDVnwv-L0tu-ik7dcMpVlThms/edit#) - наиболее близок к тому, чтобы называться ТЗ сайта)

**Comment by nat-brit** [comment]
Согласна. В принципе одно дополняет другое, поэтому оформим задачу с предложениями @kkrupovich

**Comment by Dima-Iron** [comment]
BLOCK #23810153
TRANSFER 
From | dima-iron
To | utd-content
Quantity | 175.00000 UTDEV.SKILL

Сроки по задаче 22.01. - 26.01.2018

@kkrupovich @alecvert

**Comment by Dima-Iron** [comment]
@kkrupovich @alecvert @nat-brit 

Сроки по данной задаче в связи с большим объемом подготовительных работ (по написанию Конституции) и отсутствием на текущий момент единой позиции по ряду ключевых вопросов (концепция, ЦА, наименование, продвижение и т.д.) продлеваются до 04.02.2018.

На данный момент сделана новая версия раздела корневого репозитория [Принять участие](https://github.com/u-transnet/info/wiki/2.-%D0%9F%D1%80%D0%B8%D0%BD%D1%8F%D1%82%D1%8C-%D1%83%D1%87%D0%B0%D1%81%D1%82%D0%B8%D0%B5).

Новая версия находится [здесь](https://docs.google.com/document/d/1BZMTfr7rzlTOWhM2DH-Jq55KgGvHVZOvizsR_Pz_80g/edit), фидбэк приветствуется.

В настоящее время веду работу над проектированием структуры Конституции, изучаю материал, формирую скелет и основные разделы/положения. Драфт для обсуждения в первом приближении планирую показать в конце текущей недели.

**Comment by cptn-solo** [comment]
@Dima-Iron думаю после переезда в Jira станем по-свободнее и продолжим.
