### ISSUE TITLE
[Координация #5/2018] Изменение процессов + подготовка к запуску БЧ + биржа задач и ресурсов

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#66]
Предыдущий отчет #61 
Общий план на текущую неделю [---]

## Деятельность в рамках U-TECH/TRANSNET SPACE
- Изменение процессов: jira на управление проектами, github на конфигурацию продукта (документация, код, ресурсы) + дорожная карта и вход в проект (contributing)
- Продолжаем наводить порядок в хабе

## Локальный план по направлению UTCORE
- Подготовка к запуску БЧ
- - Пробуем докер, смотрим и правим [документацию](https://github.com/u-transnet/codebase/issues/51) к docker
- Продолжаем проектирование атомарных свопов  для u-trans - фактически приступаем к реализации, исследования теперь ведутся на стороне Graphene
- Биржа задач и ресурсов

## Локальный план по направлению UTKIT
- Наводим порядок в хабе
- Приступаем к разработке

@Arteg0r @nat-brit @alecvert это план на неделю 29.01.2018 - 2.02.2018

BLOCK #23973968

TRANSFER |  
-- | --
From | cptn-solo
To | utd-architect
Quantity | 875.00000 UTDEV.SKILL

**Comment by cptn-solo** [comment]
@Arteg0r @alecvert @nat-brit 

> Продолжаем наводить порядок в хабе

За последние дни сначала в рамках [подготовки к приему гостей](https://github.com/u-transnet/info/issues/58), а потом и в рамках развития конфигурации продукта, были созданы новые репозитории - информационные ([ABOUT](https://github.com/u-transnet/ABOUT), [CONTRIBUTE](https://github.com/u-transnet/CONTRIBUTE), [UT-SCHOOL](https://github.com/u-transnet/UT-SCHOOL), [UT-CORE](https://github.com/u-transnet/UT-CORE), [UT-GAME](https://github.com/u-transnet/UT-GAME), [UT-KIT](https://github.com/u-transnet/UT-KIT)), так и предназначенные для новых направлений деятельности и компонентов будущей платформы ([UT-DESIGN](https://github.com/u-transnet/UT-DESIGN), [UT-WORKS](https://github.com/u-transnet/UT-WORKS)). Впрочем, наведением порядков дело вряд ли ограничится, и мы продолжим [оптимизировать процессы разработки](https://github.com/u-transnet/info/issues/59) - управление требованиями выносим в Jira (см. ниже)

> Подготовка к запуску БЧ

Блокчейн приближается к нам, а мы к блокчейну, готова первая версия [readme для докера](https://github.com/u-transnet/codebase/issues/51) - можно смотреть, задавать вопросы. Думаю, в рамках [задачи](https://github.com/u-transnet/Gateway/issues/9) по развертыванию среды разработки под реализацию Atomic Swaps  @netral23 сможет представить какой-то фидбэк по нашим докерам. Вообще в последние дни @mparkhomenko и @EvgeniyPolyakov была проделана довольно большая работа по обновлению кодовой базы u-transnet - были применены изменения, ранее произведенные в upstream (Bitshares). 

> UTKIT: порядок в хабе

Посмотрите, как может выглядеть доска проекта (на примере [симулятора](https://github.com/u-transnet/transnet-simulator/projects/2), спасибо @codename-art )
<img width="1362" alt="screen shot 2018-01-30 at 01 10 20" src="https://user-images.githubusercontent.com/1105555/35537275-b3d39508-055a-11e8-857a-ebd75e4f78e6.png">
Вообще репозиторий симулятора становится одним из самых продвинутых и близких к Open source. Надеюсь, репозиторий [UT-WORKS](https://github.com/u-transnet/UT-WORKS) (биржа задач и ресурсов), не сильно будет отличаться в этом плане от своего соседа (@jackal1527 @EvgeniyPolyakov ). К слову, вероятно именно на примере UT-WORKS мы сможем мигрировать управление требованиями (задачи, проекты) в jira , оставив управление конфигурацией продукта (код, документация, дорожная карта) в github. 

(to be continued)

**Comment by cptn-solo** [comment]
@u-transnet/crew  @u-transnet/app-dev @u-transnet/core-devs @u-transnet/design-gui @u-transnet/web 

**[Jira в облаке Atlassian](https://u-trans.atlassian.net/secure/Dashboard.jspa)**
> _Регистрация в проекте открытая, необходимо лишь иметь учетку в Atlassian или завести новую_

У нас есть первый [спринт](https://u-trans.atlassian.net/secure/RapidBoard.jspa?rapidView=2&projectKey=UT) в [эпике UT-WORKS](https://u-trans.atlassian.net/browse/UT-2) + заготовка под [User Story](https://u-trans.atlassian.net/browse/UT-1) в нашем новом инструменте для управления требованями к продукту - [Jira в облаке Atlassian](https://u-trans.atlassian.net/secure/Dashboard.jspa). Спринт пробный, до 2го февраля 2018, смотрим, комментируем тут или уже прямо в story. Проект отправлен на ревью команде, занимающейся в Atlassian открытой разработкой - т.ч. возможно доступ к информации о проекте не будет сильно отличаться от Github, что, на мой взгляд, хорошо.

PS: и да, там тоже есть wiki ([confluence, "конфа"](https://u-trans.atlassian.net/wiki/spaces/UT/overview)), решил подключить на всякий случай.

PPS: с хабом проинтегрировал, можно указывать в коммитах тикеты jira, детали посмотрим в доке по интеграции позже. 

(to be continued)

**Comment by cptn-solo** [comment]
@u-transnet/crew

К вопросу о терминологии - как появляются и управляются направления деятельности u-trans

Бизнес | Jira | Github
-|-|-
**Направление** => токен | **Компонент** => эпик => истории => задачи и подзадачи, включаемые в спринты | **Репозиторий** => конфигурация продукта (описание к нему - readme.md, contributing.md, wiki + код, если применимо) => дорожная карта (roadmap.md ? проект ?)

Фидбэк приветствуется

PS: пользователь взаимодействует с продуктом почти любого направления через свою учетку в блокчейне (шары/спейс) - а значит одной из точек входа всегда будет легкая регистрация (потом - интерфейсы, реализующие собственно функции продукта данного направления). И раз это так - у нас уже давно есть [наработки по форме регистрации](https://github.com/u-transnet/www-bitshares-intergation/tree/feature/bitshares_simple_registration). Надо просто помнить об этом и не начинать с нуля, когда дойдут руки @u-transnet/app-dev

**Comment by nat-brit** [comment]
Направления могут сильно различаться по своей тематике (направлению:))) Это могут быть и адресные проекты, и направления по другим тематикам, вплоть до небольших личных бизнесов... не так ли? Может стоит попробовать расписать возможные категории этих направлений?

**Comment by cptn-solo** [comment]
@nat-brit 
> Направления могут сильно различаться по своей тематике (направлению:))) Это могут быть и адресные проекты, и направления по другим тематикам, вплоть до небольших личных бизнесов... не так ли? Может стоит попробовать расписать возможные категории этих направлений?

Мне кажется, в [истории](https://u-trans.atlassian.net/browse/UT-15) появилась новая роль - инициатор направления (т.к. он может отличаться от инвестора) :)

**Comment by nat-brit** [comment]
> Мне  кажется, в истории появилась новая роль - инициатор направления (т.к. он может отличаться от инвестора) :)

Конечно, он может отличатся. Он инвестирует своим трудом, опытом, и ему нужны деньги на развитие направления, инициативные участники, и подрядчики, в отличии от инвестора:)

**Comment by cptn-solo** [comment]
@u-transnet/crew 

> **U-TECH**

Поиск брэнда платформы, апгрейд процессов разработки и управления, гитхаб медленно, но верно преображается, и начинается это с отдельных репозиториев. В то же время в Jira создана структура проектов, ссылающихся на репозитории в github. Команда активно готовится к полномасштабному запуску разработки ключевых компонентов бизнес-модели u-trans - UT-SCHOOL и UT-WORKS поверх платформы, смоделированной и тестируемой в рамках направления UT-CORE.

> **UT-KIT**

Начата разработка симулятора. Превые коммиты ушли в мастер.

> @codename-art : Сегодня заложил основу взаимодействия симулятора с внешним API, в частности нашим блокчейном. Постарался максимально абстрагироваться от конкретной реализации.
> В итоге симулятору можно подсунуть любую реализацию без изменений самого кода. Очевидная реализация это наш графен и гипотетически eos. Но в том числе и вообще бд без блокчейна, например, для тестов хочу сделать реализацию на обычной субд.


> **UT-SCHOOL**

@nat-brit @ipral50 
Сбор требований запущен, формат - User Story в Jira u-trans.
Сбор требований, к которому подключаются непосредственные представители ролей пользователей, заинтересованных в появлении образовательного направления.

> **UT-CORE**

@netral23 
Шлюзы, развертываем среду разработки, формулируем задачу, ищем исполнителя под atomic swap. В рамках развертывания среды тестируем докер платформы. 

> **UT-WORKS**

@jackal1527 @EvgeniyPolyakov 
Сбор требований запущен, формат - User Story в Jira u-trans. Сбор ролей для MVP закрывается во вторник. После этого - вычитка историй и формулировка целей/задач, доступных для принятия в работу исполнителями.
Активизировались обсуждения вопросов, связанных с выбором платформы для реализации функций биржи. 

> **UT-GAME**

@Arteg0r @cartoonka @Dvarnrock 
"Питчинг", что бы это ни значило, начался. Судя по всему, Игре все-таки быть. И это не может не радовать.

Возможно, допишу еще что-то после выходных и расставлю ссылки, а пока - за неделю это все.

**Comment by cptn-solo** [comment]
@nat-brit @Arteg0r @alecvert создал предложение транзакции на **utd-architect**
BLOCK #24087900

CREATE PROPOSAL |  
-- | --
Review period begin | —
Expiration time | February 4, 2018, 3:28:59 AM
Proposed operations | Transfer 875.00000 UTDEV from utd-architect to cptn-solo

**Comment by cptn-solo** [comment]
BLOCK #24114032

UPDATE PROPOSAL |  
-- | --
Fee paying account | cptn-solo
Proposal object id | 1.10.8087
Active approvals to add | cptn-solo

BLOCK #24111904

UPDATE PROPOSAL |  
-- | --
Fee paying account | bkmfk
Proposal object id | 1.10.8087
Active approvals to add | bkmfk
