### ISSUE TITLE
Неделя #5/2018

### ISSUE THREAD

**Issue by nat-brit** [u-transnet/info#67]
Предыдущий отчет #60 
Общий план на текущую неделю по направлениям:

## U-TECH

Оптимизация управления проектами - начинаем работать с Jira (#58,#59)
Синхронизация с GitHub (информационные репозитории+то, что касается на конфигурации продукта (документация, код, ресурсы). 
Дорожная карта (реализация в Jira) - план релизов продукта (UTCORE- расписать версии), координация разработки продукта с другими направлениями: UTDESIGN, UTKIT, UTGAME @kkrupovich 
Работа над основными документами проекта в рамках задач #64, #65 @Dima-Iron 

## UTCORE
**Подготовка к запуску БЧ**
Test: докер, документация для docker @mparkhomenko
Кастомизация BitShares-ui @EvgeniyPolyakov 
Продолжаем **проектирование атомарных свопов** для u-trans - приступаем к реализации, исследования ведутся на стороне Graphene @netral23 

UT-WORKS
**Биржа задач и ресурсов** - постановка ТЗ, планирование работ (Jira) @jackal1527 

## UTDESIGN
Сформулировать задачу: работы по сайту - заглушка, план на февраль по сайту + разработка application (ориентиры на 2Q2018) @rossul 
Разработка лого в рамках задачи #94 @RomaRAD 
Подключение к работе над сайтом копирайтера @Dima-Iron 

## UTKIT
Приступаем к разработке: задачи [сформулированы тут](https://github.com/u-transnet/transnet-simulator/issues). @codename-art 

## UTGAME
Проработка [экономики токена](https://github.com/u-transnet/Gamedev/issues/6) данного направления. Движемся по задачам: обзоры технологий, концепция прототипа, выявление требований и ограничений прототипа. @Arteg0r 

## UT-SCHOOL
Сформулировать цели по образовательному направлению (#63), приоритетность (сроки по реализации в рамках дорожной карты), если необходимо - сформировать вакансию на руководителя данного направления @kkrupovich @nat-brit

@kkrupovich @Arteg0r @alecvert план на неделю 29.01.2018 - 2.02.2018

**Comment by nat-brit** [comment]
BLOCK #24019323
From | bkmfk
To | utd-pm
Quantity | 875.00000 UTDEV.SKILL
Период 29/01/201/- 2/02/2018

**Comment by cptn-solo** [comment]
@u-transnet/crew 
@u-transnet/partners 

> **UT-SCHOOL:** Сформулировать цели по образовательному направлению

[Эпик](https://u-trans.atlassian.net/browse/US-1) для историй, связанных с образовательным направлением.

**Comment by nat-brit** [comment]
Отчет за неделю #5 [тут](https://github.com/u-transnet/info/issues/66#issuecomment-362750463)

Добавлю всего несколько пунктов:
по UT-SCHOOL: достигнута предварительная договоренность с партнером по образовательному направлению - крупным учебным заведением в Москве.
по UT-CORE: прорабатываем модель эмиссии базового актива, готовимся к запуску еще 4-х нод.
по UT-DESIGN: к сожалению, ни один из представленных  @RomaRAD эскизов лого не был утвержден. Основная сложность: очень трудно отразить (сформулировать, донести) в 2-3 словах смысл как всего проекта Transnet, так и уникальность платформы U-Trans. Десятки мозговых штурмов не прошли даром, планируем на следующей неделе закончить документ по брендингу и разложить по полкам все составляющие. @rossul 
по UT-GAME: в команде 2 новых человека: @cartoonka @Dvarnrock , кодовое название будущей игры - [ StarWay](https://github.com/u-transnet/Gamedev/issues/8), задачи [тут](https://github.com/u-transnet/info/issues/68):) 

@kkrupovich  @alecvert @Arteg0r

**Comment by cptn-solo** [comment]
@nat-brit 

> готовимся к запуску еще 4-х нод.

есть _желание_ взять еще два сервера под тестовые ноды для @netral23 (эксперименты и отладка кода atomic swap), но, возможно, есть еще кто-то, о ком мы не знаем, и кто тоже хочет собрать ядро бч из наших репозиториев ;) - вообще - эта инициатива приветствуется. Если бы у нас было больше времени мы бы давно сами подняли несколько узлов и попробовали бы сеть в действии. 

> по UT-GAME: в команде 2 новых человека: @cartoonka @Dvarnrock , кодовое название будущей игры - StarWay, задачи тут:)

Все-таки тягу человека к звездам не объяснить. Похоже, это наша природа - лезть все дальше и выше :)

**Comment by cptn-solo** [comment]
BLOCK #24161780

CREATE PROPOSAL |  
-- | --
Review period begin | —
Expiration time | February 6, 2018, 5:13:56 PM
Proposed operations | Transfer 875.00000 UTDEV from utd-pm to bkmfk

BLOCK #24161807

UPDATE PROPOSAL |  
-- | --
Fee paying account | bkmfk
Proposal object id | 1.10.8197
Active approvals to add | bkmfk

BLOCK #24161792

UPDATE PROPOSAL |  
-- | --
Fee paying account | cptn-solo
Proposal object id | 1.10.8197
Active approvals to add | cptn-solo
