### ISSUE TITLE
Иллюстрация: "Подсвеченный маршрут" на путевой структуре

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#7]
Поясняющая диаграма - фрагмент континента увеличен на фоне земного шара, покрытого схематичной паутиной путевой структуры. На увеличенном фрагменте - кружки подвижного состава "пересылают" токены станциям и путевой структуре. Путевая структура "подсвечивает" проложенный маршрут, выводя в выноске цифры объемов зарезервированных на маршрут ресурсов и каждая цифра снабжена пересчитанным в UTT значением (по аналогии с кросс-курсами) - это подводка к след. абзацу
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBU)

**Comment by cptn-solo** [comment]
Это лист CONCEPT [книги диаграмм](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Funity_concept.xml), нечто, схематично изображающее А1+А2

**Comment by iSergeevich** [comment]
![img_20170928_234803](https://user-images.githubusercontent.com/31988874/30985153-e2658fc4-a4a8-11e7-841b-77ed250d4405.jpg)
первый вариант плоский, карта мира и вычлененный кусок из нее с подробныой схемой

**Comment by iSergeevich** [comment]
![img_20170928_234822](https://user-images.githubusercontent.com/31988874/30985182-fa32bd70-a4a8-11e7-9b18-a56818d2339b.jpg)
второй вариант. считаю оптимальный. глобус с схематическими точками между пунктами с   выносками объема . без вычленения. так нагляднее сразу все видно

**Comment by iSergeevich** [comment]
цифры просто из головы. понятия не имею какая численность. просто примера ради. в схемах будет упор н алайн арт как и во всем ином. либо флэтарт это тот же лайн арт но при этом есть фоновая подложка

**Comment by cptn-solo** [comment]
Действительно, глобус выглядит интереснее карты, но это надо рисовать и смотреть как получается. 
Только одно замечание - между кружками ходит не койн U, а внутренний Ресурсный токен (ресурсный актив в Концепции). Это важно. Именно Ресурсный актив (например, "R") с ВЫНОСКОЙ в изображение БИРЖЕВОГО ГРАФИКА. 
Дело в том, что пространство TRANSNET имеет внутреннюю биржу ресурсных активов, и в каждый момент времени стоимость оказания услуги складывается из стоимости составляющих ее Ресурсов по биржевому курсу, выраженному в "койн UNITI"

**Comment by iSergeevich** [comment]
сорри. не настолько подкован в этом смысле. завтра покажу картинку. она почти готова. спать хочу не могу. поэтому завтра закончу. насчет буквы R понял. не вопрос

**Comment by iSergeevich** [comment]
вот что-то типо этого я хотел показать
![default](https://user-images.githubusercontent.com/31988874/31001025-e96fa4fc-a4f9-11e7-8191-ecc7a132caf8.png)

**Comment by iSergeevich** [comment]
разумеется все точки совпадут и добавятся токены. это лишь цифровой скетч

**Comment by cptn-solo** [comment]
глобус мне, безусловно нравится. это прям отличный пример. но это только визуальное совпадение с тем, что я думал получить. Надо объединить это визуальное представление с нашей концепцией. и еще - если мы решили делать "проволоку" в иллюстрациях - придется и глобус этот шикарный тоже превратить в проволоку. Ну, либо все иллюстрации уже делать rich graphics

**Comment by iSergeevich** [comment]
![2](https://user-images.githubusercontent.com/31988874/31030503-0456ea62-a56f-11e7-9e22-3dec19a5d6e9.png)
более плоский вариант так же на схеме есть монетка с символом R

**Comment by cptn-solo** [comment]
Последняя картинка очень неплохая по стилю и вообще - атмосфере. Надо только держать в уме:

1. если у нас одна иллюстрация будет в таком стиле - остальные прийдется делать такими же. Не уверен, что это быстрый (и вообще возможный) путь - если эта картинка часть какого-то клипарта - найдутся ли аналогичные для всех остальных иллюстраций? Если @iSergeevich  ты готов отрисовать остальные иллюстрации сам в таком же стиле - это конечно круто, можно тогда в целом заложить больше графики в иллюстрации - но оставить их тем не менее схематичными. Я бы не стал приводить прям изображения транспортных модулей из буклетов (как и путевой структуры) там, где в этом нет необходимости. 

2. Токен R нужно отвязать от стилистики монеты - ресурсный актив не является монетой (см. коммент к  #11 ). Однако идею о выноске с пересчитанной в U стоимостью хотелось бы как-то обыграть;

3. Вопрос по шаблону в целом: узлы путевой структуры - это станции, на линиях могут находиться точки меньшего размера - контейнеры в пути. Вопрос - мы же будем показывать увеличенный фрагмент как в исходных скетчах рукописных? Мы можем на увеличении показать "движение токенов" по путевой структуре (прям как на первом скетче, только не U, а R) + выноски с оценкой в U. Аналогично, на общем плане (планета) оставить выноски из узлов как на последнем изображении (нормали к поверхности) - и тоже подписать им значения и расшифровку.

**Comment by cptn-solo** [comment]
Решил попробовать порисовать, скетч в draw.io это ужас, конечно, но другого под рукой не было ничего:

<img width="364" alt="screen shot 2017-09-30 at 02 52 27" src="https://user-images.githubusercontent.com/1105555/31039912-76963482-a58a-11e7-8adc-f185f437a882.png">


@iSergeevich обрати внимание - тема "токена R" - это просто обозначение (перечисление) - каких ресурсов (A,B,..Z) и в каком количестве требуется для выполнения заказа - это и есть "расчет маршрута".

**Comment by alecvert** [comment]
@iSergeevich @kkrupovich глобус круто, но отталкивают вот эти выноски http://prntscr.com/gvgi3i , как будто шипы http://prntscr.com/gvgikm

**Comment by cptn-solo** [comment]
> @iSergeevich @kkrupovich глобус круто, но отталкивают вот эти выноски http://prntscr.com/gvgi3i , как будто шипы http://prntscr.com/gvgikm

ИМХО кто-то пересмотрел ужастиков в детстве просто. 
Но я согласен, что можно оставить только подписанные выноски, а пустые убрать.

Однако не будем забывать о главном назначении данной иллюстрации. @iSergeevich , коллега, иллюстрации - это не просто рисунки. Это графическое выражение того, что написано в тексте, либо объяснено моими схемами (которые мне не так-то просто рисовать - но я это делаю, пытаюсь тебе помочь). И там глобус если и предполагается, то только в качестве фонового изображения. С учетом того, что мы все хотим показать в проволоке и максимально схематично - глобус тут вообще скорее просто как идея, которую обязательно надо сохранить и развить - но применить в другом месте где-то. 
Еще раз прошу ознакомиться с моей схематичной подсветкой и взять эту схемку за основу, иначе мы не поможем ничем абсолютно тем несчастным, кто будет пытаться читать и понимать текст нашего концепта.

**Comment by iSergeevich** [comment]
![3](https://user-images.githubusercontent.com/31988874/31467191-90c93d92-aef2-11e7-9274-6bed0a500e34.png)
утром еще вариант прикреплю

**Comment by alecvert** [comment]
@iSergeevich @kkrupovich где вариант?

Крайний вариант абсолютно не подходит на мой взгляд.

**Comment by cptn-solo** [comment]
@alecvert абсолютно не подходит - не ответ. 
@iSergeevich по пунктам:
1. "подсвеченный" маршрут надо бы пожирнее выделить (без фанатизма, но этот маршрут должен выделяться заметнее;
2. На задник положить карту континентов с сетью - то, что в круге - это только "зум";
3. монету на этой иллюстрации не обязательно показывать, а если показывать - в правой колонке цифры внизу, под "суммой" в U (Эта сумма - и есть пересчитанная в монеты, в UTT);

Потом посмотрим дальше что получается.

**Comment by iSergeevich** [comment]
ок

**Comment by iSergeevich** [comment]
![4](https://user-images.githubusercontent.com/31988874/31647464-d518e79e-b321-11e7-88a5-5d22cd4c4c32.png)

**Comment by cptn-solo** [comment]
насчет зума - не вижу выделения маршрута  (забыл? это первый пункт был)
Карту можно подрезать до какой-то небольшой области - четверти Африки, думаю, хватит, см. аналогичный коммент в #6
