### ISSUE TITLE
[Координация UT-Game #6/2018] Отбор идей, выбор инструментов, смежные вопросы

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/info#70]
@kkrupovich @nat-brit 

[Предыдущий недельный отчет](https://github.com/u-transnet/info/issues/68)

Коллеги, докладываю о работах на этой неделе 5-9 февраля  (тут, по старинке):

- продолжаем брейнштормить и шлифовать концепты в рамках [этой](https://github.com/u-transnet/Gamedev/issues/10) и [этой](https://github.com/u-transnet/Gamedev/issues/9) задач
- исследую менеджер [hacknplan](http://hacknplan.com ) с целью понять пригодность его для дальнейшей работы
- парни предложили любопытное  и гибкое решение по коллаборации - https://realtimeboard.com/app/. @kkrupovich @nat-brit, посмотрите, вдруг вам тоже пригодится в работе
- обсудили с @kkrupovich диаграммы, услышал его мнение и сделал выводы относительно возможного баланса игра vs точная модель
- собираюсь изучить текущий опыт работы с требованиями команды в jira для понимания того, нужно ли такой процесс организовывать в игровом направлении, и если да, то как
- планирую глубже ознакомиться с наработками по симулятору

**Comment by Arteg0r** [comment]
BLOCK #24246011

TRANSFER |  
-- | --
From | arteg0r
To | utd-architect-game
Quantity | 875.00000 UTDEV.SKILL

**Comment by Arteg0r** [comment]
Итак, вот чего мы добились за прошлую неделю:

- два концепта, Cities и Asteroids, пережили брейнштормы и **продолжили развиваться**, а вот шикарная идея с прогрессорством **не прижилась**. 

- менеджер hacknplan выглядит и работает как jira, из которой вынесли лишнее ) понравилась game design model - иерархическая структура компонентов игры, на которую можно завязывать таски (близка идее components в jira). **Заключение следующее**: данный инструмент выглядит пригодным к использованию на стадии продакшена

- понял, что нужно **пригласить** @kkrupovich на встречи смежных направлений с лекцией на тему i-диаграмм, чтобы он представил парням ключевые идеи

- изучил подход к работе с требованиями/стори в jira. Изящно, но к нашей игровой разработке сходу не приложишь. Тоже будем описывать сценарии для проверки концептов, но **не по данной схеме**

- впечатлился работой Артема по симулятору. Несмотря на то, что столь подробная схема токенизации с большой вероятностью минует прототип игры, непременно **позову** его рассказать о своей работе на встречу со смежниками

@kkrupovich @nat-brit 
Прошу согласовать закрытие итерации.

**Comment by cptn-solo** [comment]
@Arteg0r @alecvert @nat-brit предложил транзакцию на **utd-architect-game** : 
BLOCK #24428607

CREATE PROPOSAL |  
-- | --
Expiration time | February 16, 2018, 12:15:07 AM
Proposed operations | Transfer 875.00000 UTDEV from utd-architect-game to arteg0r
