### ISSUE TITLE
[Координация UT-Game #7/2018] Генерация и проверка идей, манифест, библиотека

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/info#72]
[Предыдущая](https://github.com/u-transnet/info/issues/70)

На этой неделе, 12-16 февраля, у нас ожидается:

- Составление новых концептов - Planets и Pioneers
- Доработка и развитие идей Cities и AsteroidRush
- Попытаемся набросать черновик миссии/манифеста игрового направления. Есть предчувствие, что подобный документ поможет нам отсеять нужные идеи, а также ответит на следующий вопрос: какие ценности, идеи, знания мы собираемся донести игрой главному стейкхолдеру - нашим игрокам
- Решили проводить еженедельно по понедельникам : 

1. планерку для координации работ внутри направления 
2. собрание с представителями смежных направлений для обмена информацией, опытом, наработками в разнообразных форматах: сессий вопросов-ответов, докладов, совместных обсуждений предложенных тем и коллективных оценок гипотез. Первая такая встреча состоялась при участии @kkrupovich @nat-brit 13.02.18

- Для повышения знаний о блокчейне среди сотрудников направления, ускорения процесса обучения организуем совместную библиотеку. Есть идея сделать ее не в виде скучно-практичного spreadsheet, а в виде "полочек" на базе realtimeboard
- Помочь @nat-brit синхронизировать нашу дорожную карту с глобальной 
- Обсудить с @kkrupovich @nat-brit возможности работы с аудиторией адептов Skyway для проведения опросов и тестирования относительно игровых предпочтений

**Comment by cptn-solo** [comment]
@Arteg0r @nat-brit 
> Есть идея сделать ее не в виде скучно-практичного spreadsheet, а в виде "полочек" на базе realtimeboard

и через нее обрастать сообществом, тащить туда UT-SCHOOL и UT-WORKS

**Comment by Arteg0r** [comment]
BLOCK #24430336


TRANSFER |  
-- | --
From | arteg0r
To | utd-architect-game
Quantity | 875.00000 UTDEV.SKILL

**Comment by nat-brit** [comment]
> идея  сделать ее не в виде скучно-практичного spreadsheet, а в виде "полочек" на базе realtimeboard

давайте обсудим подробнее, идея интересная:)

**Comment by Arteg0r** [comment]
А не подвести ли итоги прошлой итерации? Давно пора! 

- Завершили работу над идеей Cities
- Развивали и уточняли AsteroidRush
- Сформировали (не без риска для ментального здоровья) две новые идеи: Planets и Pioneers
- Набросал [черновик](https://docs.google.com/document/d/1XwquQrpDzw4744zCq3kY5xe-mW05F7LOLdne6w-q6js/edit?usp=sharing) миссии/манифеста игрового направления
- Идея о библиотеке, увы, осталась идеей. Реализация в realtimeboard переехала на следующую итерацию
- Синхронизировались с @nat-brit по поводу дорожных карт, а также обсудили с @alecvert порядок исследования аудитории адептов Skyway

@kkrupovich @nat-brit, прошу итерацию закрыть.

**Comment by nat-brit** [comment]
По библиотеке обязательно проработаем скоро:) @Arteg0r

**Comment by cptn-solo** [comment]
@Arteg0r @nat-brit @alecvert предложил транзакцию на учетке **utd-architect-game**:
BLOCK #24650059

CREATE PROPOSAL |  
-- | --
Review period begin | —
Expiration time | February 23, 2018, 6:15:56 PM
Proposed operations | Transfer 875.00000 UTDEV from utd-architect-game to arteg0r
