### ISSUE TITLE
[Координация UT-Game #8/2018] Доработка отобранных идей

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/info#73]
[Предыдущая задача](https://github.com/u-transnet/info/issues/72)

Итак, на этой неделе беру 4 дня (23.02 не работаю). 

В этой итерации:

- Приняли решение остановиться на 4 идеях: Cities, AsteroidRush, Planets и Pioneers. Их будем представлять в ходе будущей питч-сессии с участием всей команды U-Tech. 
- На этой неделе обсуждаем/разрабатываем AsteroidRush, Planets и Pioneers
- В рамках встречи со смежными направлениями послушали ~~Конфуция~~ эээ, пардон, @kkrupovich, который рассказал как обычно увлеченно и увлекательно про схему движения токенов, нюансы работы графена и другие удивительные вещи
- С прошлой неделе переехала задача с библиотекой, попробую что-то соорудить в realtimeboard
- Из мелочей, на подумать: 
1) открыть "представительство" в jira, чтобы @kkrupovich смог ссылаться в отчетах 
2) как может выглядеть схема движения токенов семейства UTGAME между разработчиками/игроками/играми UT-Gamedev

@kkrupovich @nat-brit

**Comment by Arteg0r** [comment]
BLOCK #24625337

TRANSFER |  
-- | --
From | arteg0r
To | utd-architect-game
Quantity | 700.00000 UTDEV.SKILL

**Comment by Arteg0r** [comment]
Итоги прошлой недели:

1. Продолжали обсуждать и работать над концепциями: 

- [AsteroidRush](https://realtimeboard.com/app/board/o9J_kzr93Fs=/) 
- [Planets](https://realtimeboard.com/app/board/o9J_kzruL0M=/)  
- [Pioneers](https://realtimeboard.com/app/board/o9J_kzqgWFM=/)

2. Прототип [библиотеки в realtimeboard](https://realtimeboard.com/app/board/o9J_kzqre8I=/)
Чего хочется получить от нее в конечном счете:
- наглядность и "тактильность" в духе сквевоморфизма/material дизайна
- тематическое разделение через фреймы
- система вопрос/ответ среди читателей через систему комментариев, взаимопомощь с объяснениями для ускорения усвоения информации
- краткие заметки о прочтенном материале, помогающие читателям быстро сориентироваться/уловить суть, основные мысли материала
- содержание библиотеки изменяется участниками совместно

3. Из мелочей, взятых на подумать:
- видимо, в след. итерацию будем переноситься в jira, согласно обновленному [регламенту](https://github.com/u-transnet/info/wiki/2.4.-%D0%A0%D0%B5%D0%B3%D0%BB%D0%B0%D0%BC%D0%B5%D0%BD%D1%82-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%8B-%D1%81%D0%BE-Skill-%D0%B2-Jira-u-trans)
- по схеме движения токенов семейства UTGAME лишь одни догадки. продолжаю думать в фоновом режиме

@kkrupovich @nat-brit, прошу закрывать.

**Comment by cptn-solo** [comment]
@Arteg0r 
BLOCK #24900208

CREATE PROPOSAL |  
-- | --
Review period begin | —
Expiration time | March 4, 2018, 11:25:24 AM
Proposed operations | Transfer 700.00000 UTDEV from utd-architect-game to arteg0r

**Comment by Arteg0r** [comment]
BLOCK #24907360

UPDATE PROPOSAL |  
-- | --
Fee paying account | bkmfk
Proposal object id | 1.10.8528
Active approvals to add | bkmfk
