### ISSUE TITLE
[Координация UT-Game #9/2018] Доработка отобранных идей

### ISSUE THREAD

**Issue by Arteg0r** [u-transnet/info#74]
[Предыдущая задача](https://github.com/u-transnet/info/issues/73)

На этой неделе оказался разорван домашними делами, будет справедливо в сумме посчитать ее как 3 дня: 26-27, 28, 1, сегодня день не учитываю. Поскольку отчетная задача тоже запоздала, прошу сразу ее закрывать после объявления работ:

- работали в рамках концептов Cities, AsteroidRush, Planets и Pioneers, подходим к подготовке презентаций для защиты идей
- неожиданно взяли в разработку идею [Pioneers AR](https://docs.google.com/document/d/1_Qtoed21-8klGHSUly-mb6yoyjHTw0_ncj32zUUwek0/edit?usp=sharing)
- работы в рамках [библиотеки в realtimeboard](https://realtimeboard.com/app/board/o9J_kzqre8I=/)
- Также до конца недели - миграция в jira

@kkrupovich @nat-brit

**Comment by Arteg0r** [comment]
BLOCK #24868079


TRANSFER |  
-- | --
From | arteg0r
To | utd-architect-game
Quantity | 525.00000 UTDEV.SKILL

**Comment by cptn-solo** [comment]
@Arteg0r 
BLOCK #24900150

TRANSFER |  
-- | --
From | utd-architect-game
To | arteg0r
Quantity | 525.00000 UTDEV
