### ISSUE TITLE
Иллюстрация: "Command & Conquer" - карта с областями нагрузок

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#8]
Этот абзац как раз можно проиллюстрировать "картой стратегического планирования инвестиций" - с зелеными, желтыми, красными областями
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBc)

**Comment by iSergeevich** [comment]
![default](https://user-images.githubusercontent.com/31988874/31064353-ced0a9ea-a754-11e7-965b-a5e4eda95cff.png) что-то вот такое лезет

**Comment by cptn-solo** [comment]
слушай, эта карта с выносками под стратегическое планирование неплохо кстати подойдет, не забрасывай ее. только область под точкой с красной выноской закрасить красным (европу), с желтой - желтым и т.д. 
И действительно - сейчас вижу, что напрашивается какой-то ряд цифр на каждую выноску, давай может добавим что-то подобное моим колонкам цифр со скетча из #7 ? Там ведь тоже идет выноска, упирающаяся в колонку цифр вида "A: 123.33", т.ч. будет перекликаться

**Comment by iSergeevich** [comment]
принял

**Comment by iSergeevich** [comment]
по цветам нужно решить четко гамму и все в них буду делать

**Comment by iSergeevich** [comment]
![2](https://user-images.githubusercontent.com/31988874/31377861-e72a3d02-adc2-11e7-83ad-4262dcb83604.png)

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich Хорошо, что иконки обозначают? Так очень неплохо. Решить по цветам и ок. Цвета должны быть такие же как в фирменном стиле.

**Comment by iSergeevich** [comment]
@alecvert описание цифр на выносках 
https://github.com/u-transnet/info/issues/8#issuecomment-333454337 
https://github.com/u-transnet/info/issues/7

**Comment by cptn-solo** [comment]
@iSergeevich @alecvert коллеги. зачем целиком континенты залили цветом? Я начинаю думать, что работаю с китайцами - те тоже в любой непонятной ситуации все "понимают" как им удобно.
Красный, желтый, зеленый - цвета светофора, предупреждения, опасности, безопасности. Это очевидно.
Заливка областей - явно по степени загрузки этой области. То есть берется, например, север полуострова Индостан и заливается красным, или сеть путей (линии) красятся в красный. 
У меня слов честно говоря нет. 
Я хочу, чтобы мне проиллюстрировали текст. Чтобы это сделать - нужно его хотя бы попытаться понять.

**Comment by iSergeevich** [comment]
![3](https://user-images.githubusercontent.com/31988874/31493887-8b732ab0-af6a-11e7-8c19-b88ff189cb10.png)
без светофора и заливки всей карты

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich выглядит классно, но что обозначает и для чего?

**Comment by cptn-solo** [comment]
@iSergeevich фиолетовый что должен обозначать в концепции "светофора"? "Мне фиолетово"? ;) давайте сделаем все же 3 цвета, зеленый, желтый и красный. Зеленый и желтый где-нибудь на дальних локациях, а  красный (перегрузка мощностей) - где-нибудь в Индии, например. 
И еще  - мы можем "рыбий глаз" сделать, чтобы это место как-то "приблизить" - это ж добыча инвестора - нехватка мощностей, значит, в этот район надо вваливать инвестиции! Подумай, как показать на иллюстрации "ахтунг, нужны деньги". Пожар, восклицательный знак, красный цвет точек и связей между ними на схеме сети выделенного участка, ну я не знаю.

**Comment by iSergeevich** [comment]
пожар явно не нужно. восклицательный знак самое оно, либо красные точки и связи. зум сделаю

**Comment by iSergeevich** [comment]
![4](https://user-images.githubusercontent.com/31988874/31630500-346ca8a4-b2d0-11e7-9fd3-536ea2a4f4fd.png)

**Comment by cptn-solo** [comment]
@iSergeevich @alecvert @jackal1527 это хорошая иллюстрация. Спасибо.
