### ISSUE TITLE
Иллюстрация: иерархия затрат, складывающихся в токен адресного проекта

### ISSUE THREAD

**Issue by cptn-solo** [u-transnet/info#9]
Поясняющая диаграма - иерархическая структура затрат с балансами инфраструктурных активов
Коммент в исходнике [тут](https://docs.google.com/document/d/1BNSpJDJ44YF01ByEYk9a3-lKQGOIMAX7YxCT9VAX0Ro/edit?disco=AAAABSMHQBg)

**Comment by cptn-solo** [comment]
Возможно, в качестве основы подойдет диаграмма F0 из [книги диаграмм](https://www.draw.io/#Hu-transnet%2Finfo%2Fmaster%2Funity_concept.xml)

<img width="656" alt="screen shot 2017-09-26 at 00 12 00" src="https://user-images.githubusercontent.com/1105555/30831308-a48ffeec-a24f-11e7-8282-164457148e1c.png">

**Comment by iSergeevich** [comment]
![default](https://user-images.githubusercontent.com/31988874/31226244-d66fc982-a9ee-11e7-92b1-6cbf3c2228ab.jpg)
родил таки. 4 вариант инфографики)) если всем нравится буду сводить стилистику всего к этому. лайнарт

**Comment by cptn-solo** [comment]
корректирую вИдение:
1. Нижний шар - структура адресного актива - это и есть один из 6тиугольников, это д.б. показано не двумя стрелками, а "зумом", как у меня.
2. Портфельный актив - это весь нижний (зум) шар, поэтому пунктирная стрелка должна  вести не в "подвижной состав, а в желтый круг (который по-идее должен быть заменен шестиугольником)

**Comment by iSergeevich** [comment]
![default](https://user-images.githubusercontent.com/31988874/31266313-9f91d8f8-aa8c-11e7-9456-c9c0086410c9.jpg)

**Comment by iSergeevich** [comment]
![2](https://user-images.githubusercontent.com/31988874/31266318-a7237ca2-aa8c-11e7-8373-b5f18e7db4a8.jpg)

**Comment by iSergeevich** [comment]
![3](https://user-images.githubusercontent.com/31988874/31266335-b8701db2-aa8c-11e7-8025-9fb7a9d2603d.jpg)

**Comment by cptn-solo** [comment]
Логически все хорошо. Один только момент, который был довольно важен в исходной моей иллюстрации - это собственно сама "структура" - это в числе прочего еще и "пропорция" - поэтому я использовал секторный график в качестве фигуры, подписанной как "структура активов". @iSergeevich я бы добавил в левый верхний угол шестиугольника (есть немного места между зеленым и синим кругами) небольшую иконку секторной диаграммы из любого клипарта
<img width="254" alt="screen shot 2017-10-06 at 10 55 41" src="https://user-images.githubusercontent.com/1105555/31268456-06f86bae-aa85-11e7-8608-6c208a9a4bfd.png">
<img width="83" alt="screen shot 2017-10-06 at 10 54 53" src="https://user-images.githubusercontent.com/1105555/31268457-07227142-aa85-11e7-8107-58838dee3d07.png">

**Comment by iSergeevich** [comment]
не вопрос. какой вариант слева или справа?

**Comment by cptn-solo** [comment]
Блин, хороший вопрос. ИМХО слева строже, а справа довольно много цветов, и их надо будет приводить в соответствие с остальными диаграммами. т.ч. я бы наверное посмотрел левый. 

И ЕЩЕ - давайте развернем стрелку от структуры к портфелю, а не наоборот. Чего-то я все же думаю, что у нас стрелки должны идти по иерархии активов. Т.е. от фиата и крипты через  ресурсные и инфраструктурные токены к самому высокоуровневому - портфельному токену адресного проекта. А то сейчас у нас две точки входа из внешней экономики получается, а это не так на самом деле.

**Comment by iSergeevich** [comment]
![default](https://user-images.githubusercontent.com/31988874/31271308-8663c756-aaa0-11e7-8043-cb311430aa4f.jpg)

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich  1. Давайте исходить из цветовой гаммы нашего будущего фирменного стиля.
2.  Шрифт текста должен быть более айтишным, у нас же не комикс , типа Courier New http://prntscr.com/gtzruc (как пример), надо выбрать. И опять же его использовать потом как фирменный стиль.
3. Давайте добавим живости иконками , но тоже в айтишном стиле, которые потом в презах и инфографике схематичной будем использовать. То есть, Ваня, где базовый актив, там будет монохромный лого , транснет ок и там Пространство Транснет должно быть наверное, актив станций Станцию сделай иконку, Актив земельного участка тоже. Отличие просто путевой структуры , станции, подвижного состава и т д от актива, что актив может быть та же иконка , но пунктиром, либо в круге земного шара нашем цифровом.  Нужно придумать отличие иконки реальной составляющей транснет спейс от актива реальной составляющей. И везде использовать.

**Comment by iSergeevich** [comment]
шрифты и цвета переехали в ветку https://github.com/u-transnet/www-teaser/issues/8#issuecomment-339231720 все равно на сайте тоже использовать

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich  начсет шрифта предложение взять какой то из этих
https://www.behance.net/gallery/23503137/TT-Supermolot - шрифт класс! Или вот это ? http://prntscr.com/gvqsit

фирменные цвета - морская волна, синий, красный, черный . Не катит. У кого какие предложения?

**Comment by iSergeevich** [comment]
зеленый и его оттенки. мятный мб
оранж + черный
голубой + фиолетовый, анаглиф
можно привязать к цветам скайвэй

**Comment by iSergeevich** [comment]
шрифт руссосанс или молот. принято. скачал

**Comment by cptn-solo** [comment]
Шрифт ок. Цвета лучше показывать цветами, а не "синий", "красный", "черный"
И вообще, вы так уютно расположились в задаче под саму важную иллюстрацию, что у меня прям даже как-то слов нет, чтобы вас прогнать отсюда. Закругляйтесь.

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich прикольная идея иконок http://prntscr.com/gvrs7f Как считаете?

**Comment by cptn-solo** [comment]
> @kkrupovich @iSergeevich прикольная идея иконок http://prntscr.com/gvrs7f Как считаете?

Норм. Как вариант.

**Comment by iSergeevich** [comment]
@kkrupovich @alecvert если считаете нужным - отрисую их

**Comment by alecvert** [comment]
@iSergeevich @kkrupovich где продолжение?

**Comment by cptn-solo** [comment]
@iSergeevich да, давайте уже сводить со шрифтами и стилями

**Comment by iSergeevich** [comment]
![4](https://user-images.githubusercontent.com/31988874/31635209-68533c50-b2df-11e7-94a0-a1e7603267bd.jpg)

**Comment by cptn-solo** [comment]
@iSergeevich @alecvert это ВАУ. Мне очень нравится и стиль, и содержание (правда, содержание тут по-моему изначально мое - но @iSergeevich удалось сделать из моего ..на конфетку, ИМХО это пока эталон. К этому надо стремиться во всех иллюстрациях.

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich да, мне нравится. Просто и со вкусом.

**Comment by iSergeevich** [comment]
спасибо!

**Comment by iSergeevich** [comment]
![5](https://user-images.githubusercontent.com/31988874/31966401-00fe2902-b924-11e7-8052-18055d789692.png)
и попутно для сайта визуал 
![default](https://user-images.githubusercontent.com/31988874/31966477-44bda244-b924-11e7-88e5-6c0cf1df6ba5.png)

**Comment by cptn-solo** [comment]
@iSergeevich ну я не знаю, прикольно выглядит, конечно, но зачем к этой задаче опять? она и так тяжеленная - надо убирать отсюда шрифты и стили в другое место куда-то.

**Comment by iSergeevich** [comment]
@kkrupovich https://github.com/u-transnet/www-teaser/issues/8#issuecomment-339231720 я перенес туда буквы и цвета, блин ка же медлено все с телефона делать...) он аж троить начал когда в буфер столько инфы вогнал))))

**Comment by cptn-solo** [comment]
@iSergeevich спасибо, норм

**Comment by alecvert** [comment]
@kkrupovich @iSergeevich  http://prntscr.com/h2apo9 непонятно , что к чему и в стиле футурамы, мультяшно как комиксы что ли

**Comment by cptn-solo** [comment]
> @kkrupovich @iSergeevich http://prntscr.com/h2apo9 непонятно , что к чему и в стиле футурамы, мультяшно как комиксы что ли

На самом деле здравое зерно есть - выноски, уводящие вниз, и ведущие к "лежащему в основании" электронному представлению элемента.
